import type { Page } from '../App'

interface IndigoBuntingProps {
  onNavigate: (page: Page) => void
}

export default function IndigoBunting({ onNavigate }: IndigoBuntingProps) {
  return (
    <>
      <div className="species-hero-image-wrap">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/6/62/Indigo_Bunting_by_Dan_Pancamo_4.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original"
          alt="Male Indigo Bunting in full breeding plumage — intense cerulean blue from bill to tail — perched on a wild grass seed head"
          className="species-hero-image"
          style={{ objectPosition: 'top center' }}
          loading="eager"
        />
        <div className="species-hero-image-credit">
          {/* Photo: Dan Pancamo · <a href="https://commons.wikimedia.org/wiki/File:Indigo_Bunting_by_Dan_Pancamo_4.jpg" target="_blank" rel="noopener noreferrer">CC BY-SA 2.0</a> via Wikimedia Commons */}
          Photo: Dan Pancamo&nbsp;·&nbsp;
          <a href="https://commons.wikimedia.org/wiki/File:Indigo_Bunting_by_Dan_Pancamo_4.jpg" target="_blank" rel="noopener noreferrer">CC BY-SA 2.0</a>
          &nbsp;via Wikimedia Commons
        </div>
      </div>

      <section className="hero">
        <div className="hero__eyebrow">Meet Your Neighbors</div>
        <h1>Indigo Bunting</h1>
        <p className="hero__lead">
          The male Indigo Bunting is the most intensely blue songbird in eastern
          North America — and the blue is not pigment. It is structural coloration:
          physics made visible in feathers. This small bird also navigates by starlight,
          crosses the Gulf of Mexico twice a year, and shares its fall habitat
          with migrating monarchs.
        </p>
      </section>

      

      <div className="page">
        <section aria-labelledby="biology-heading">
          <h2 id="biology-heading">A color that is physics, not paint</h2>
          <p>
            The male Indigo Bunting (<em>Passerina cyanea</em>) carries no blue pigment.
            Its intense blue is produced entirely by microscopic feather structures
            that refract light — the same physics that makes the sky appear blue.
            In low light or shade, males look black. Under full sun, they appear
            almost electric. The color is real, but it is not stored in the feathers.
            It is generated by the angle of light and the geometry of structure.
          </p>
          <p>
            The female is plain brown with faint streaking — cryptic plumage
            evolved for nest concealment. Males use brilliant color to advertise
            and defend territory; females use camouflage to protect active nests.
            This dimorphism means most people only report seeing the males.
            When you find a plain brown bird in brushy habitat in summer, look
            carefully: it may be a nesting female incubating eggs and ferrying insects to chicks whose bones and feathers are still forming.
          </p>
        </section>

        <section aria-labelledby="navigation-heading">
          <h2 id="navigation-heading">Navigating by stars learned before first flight</h2>
          <p>
            Indigo Buntings are among the most thoroughly studied examples of
            stellar navigation in birds. Nestlings learn the axis of stellar rotation
            — the star pattern rotating around Polaris — before they leave the nest.
            They use this learned reference to navigate during nocturnal migration
            throughout their entire lives, correcting course across hundreds of miles
            using a map they assembled as chicks.
          </p>
              <figure className="species-content-photo species-content-photo--right">
                <img
                  src="https://upload.wikimedia.org/wikipedia/commons/f/f0/IndigoBunting.jpg"
                  alt="Male Indigo Bunting in full breeding plumage — iridescent blue that is structural, not pigment"
                  loading="lazy"
                />
                <figcaption>
                  The male Indigo Bunting contains no blue pigment. The feathers have microstructures that refract and scatter light, producing vivid blue only in direct sun. In shadow, the male appears brown — identical to the female whose plain coloration evolved to keep her invisible on the nest.
                  <span className="photo-credit"> Photo: Trisha Shears · <a href="https://commons.wikimedia.org/wiki/File:IndigoBunting.jpg" target="_blank" rel="noopener noreferrer">CC BY-SA 2.0</a> via Wikimedia Commons</span>
                </figcaption>
              </figure>

          <p>
            Every spring, a bunting weighing less than half an ounce crosses the
            Gulf of Mexico in a single overnight flight — 500 to 600 miles of
            open water — at altitude, guided by stars, running on fat reserves
            built in the days before departure. The bird that arrives at your
            yard in May flew non-stop over open ocean the night before. That is
            not a routine commute. That is a biological feat worth protecting.
          </p>
        </section>

        <section aria-labelledby="threats-heading">
          <h2 id="threats-heading">A two-front challenge: wintering grounds and fragmented habitat</h2>
          <p>
            Approximately 28 million Indigo Buntings breed in North America, but
            the species has declined roughly 22% since 1966. The primary cause is
            deforestation on wintering grounds in Central America, Cuba, and the
            Caribbean — a reminder that backyard habitat work, while essential,
            does not fully close the gap if wintering forest is cleared.
          </p>
          <p>
            The secondary pressure is Brown-headed Cowbird nest parasitism, which
            is highest at habitat edges within 100 meters of forest. Indigo Buntings
            nest in brushy edge habitat — exactly the fragmented strips that dominate
            suburban landscapes — making parasitism risk higher in narrow, isolated
            patches. Wider habitat corridors reduce cowbird access and improve
            nesting success.
          </p>
        </section>

        <div className="action-panel">
          <h2 style={{ marginTop: 0 }}>Native shrubs at the yard edge, white millet in fall, and seed heads left standing into October</h2>

          <figure className="species-content-photo species-content-photo--left">
            <img src="https://upload.wikimedia.org/wikipedia/commons/6/63/Asclepias_tuberosa_2.jpg" alt="Butterfly weed in bloom with orange flower clusters" loading="lazy" />
            <figcaption>
              Indigo buntings follow native seed plants through late summer and autumn. Native milkweeds, coneflowers, and grasses carrying seeds into October provide the stopover fuel that sustains a migration moving by star-navigation from Minnesota to Mexico.
              <span className="photo-credit"> Photo: Tortie tude&nbsp;·&nbsp;<a href="http://creativecommons.org/publicdomain/zero/1.0/deed.en" target="_blank" rel="noopener noreferrer">CC0</a>&nbsp;via Wikimedia Commons</span>
            </figcaption>
          </figure>
          <ol className="step-list">
            <li>
              <strong>Plant native brushy shrubs at yard edges.</strong>{' '}
              Native dogwood (<em>Cornus</em> spp.), elderberry (<em>Sambucus canadensis</em>),
              native plum (<em>Prunus americana</em>), and viburnum provide breeding
              habitat structure. Leave brushy unmowed areas through July to protect
              active nests.
            </li>
            <li>
              <strong>Offer white millet during spring and fall migration.</strong>{' '}
              Scatter white millet on the ground or on a low platform feeder starting
              late April and again in August and September. White millet is the preferred
              feeder food for buntings during migratory stopovers.
            </li>
            <li>
              <strong>Plant native seed-bearing wildflowers.</strong>{' '}
              Rudbeckia, Coreopsis, and native Amaranth provide seed through late summer
              and fall, supporting both resident buntings and migrants fueling up
              for the Gulf crossing.
            </li>
            <li>
              <strong>Stop insecticide applications on shrubs and native plants from May through August.</strong>{' '}
              A female Indigo Bunting feeding nestlings carries soft-bodied insects and small
              caterpillars to the nest cup several hundred times per day — pulled from the canopy
              of native shrubs within 150 feet of the nest. Broad-spectrum insecticide applications
              on those shrubs remove the prey the nestlings need during the 9 to 12 days between
              hatch and fledge. Systemic products applied as a soil drench or nursery pre-treatment
              suppress caterpillar populations in treated plants for weeks after application. The
              full picture is in the{' '}
              <button className="link-button" onClick={() => onNavigate('pesticide-guide')}>
                Pesticides &amp; Your Habitat guide
              </button>
              .
            </li>
          </ol>
        </div>

        <section aria-labelledby="connection-heading">
          <h2 id="connection-heading">Shared habitat with monarchs in fall</h2>
          <p>
            Indigo Buntings and monarch butterflies use the same brushy native meadow edges
            as staging and migratory habitat in fall. Both species move through goldenrod,
            native seed heads, and wildflower corridors at the same time of year.
            One habitat installation — a brushy edge featuring goldenrod, native asters,
            and native shrubs — can serve migrating monarchs nectaring on flowers and
            migrating buntings eating seeds from the same plants simultaneously.
          </p>
          <p>
            This is the core argument Camp Monarch makes visible: when you restore
            habitat functions, you do not choose between species. You build a system
            that supports dozens of them at once.
          </p>
        </section>

        <div className="action-panel" style={{ marginTop: '2rem' }}>
          <p style={{ margin: 0 }}>
            <strong>Ready to build bunting habitat?</strong>{' '}
            <button className="link-button" onClick={() => onNavigate('choose-a-plant')}>
              Choose a native plant
            </button>
            {' '}to add brushy edge structure and seed sources,{' '}
            <button className="link-button" onClick={() => onNavigate('plant-milkweed')}>
              plant milkweed
            </button>
            {' '}to strengthen the shared habitat that supports both monarchs and migrants,
            understand how insecticide use reduces the caterpillar supply at the{' '}
            <button className="link-button" onClick={() => onNavigate('pesticide-guide')}>
              Pesticides &amp; Your Habitat guide
            </button>
            , and see how the brushy edge layer connects to the full yard structure in the{' '}
            <button className="link-button" onClick={() => onNavigate('habitat-layers')}>
              Habitat Layers guide
            </button>
            .
          </p>
        </div>
      </div>
    </>
  )
}
