import type { Page } from '../App'

// Photo data — Wikimedia Commons (CC BY-SA / CC BY / Public Domain) and iNaturalist open-data.
// Verified 2026-05-18. Attribution listed at bottom of page.
const PHOTO_FALLBACK =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540"><rect width="100%" height="100%" fill="%23e8f5e9"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-size="48" fill="%234caf50">🌿</text></svg>'

type Status = 'common' | 'declining' | 'endangered'

interface Species {
  id: string
  name: string
  scientificName: string
  emoji: string
  shortDesc: string
  status: Status
  photo: string
  photoCredit: string
  page: Page | null
  habitatTags: string[]
}

const SPECIES: Species[] = [
  {
    id: 'monarch',
    name: 'Monarch Butterfly',
    scientificName: 'Danaus plexippus',
    emoji: '🦋',
    shortDesc: 'Lays eggs only on milkweed — a plant eliminated from roughly 165 million acres of American farmland since 1996. The eastern population has dropped from 900 million in the 1990s to about 60 million today.',
    status: 'endangered',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Monarch_Butterfly_Danaus_plexippus_Male_2664px.jpg/960px-Monarch_Butterfly_Danaus_plexippus_Male_2664px.jpg',
    photoCredit: 'Kenneth Dwain Harrelson / CC BY-SA 3.0',
    page: 'why-monarchs',
    habitatTags: ['milkweed', 'open-meadow', 'garden'],
  },
  {
    id: 'firefly',
    name: 'Firefly',
    scientificName: 'Photinus pyralis',
    emoji: '✨',
    shortDesc: 'Larvae spend up to two years hunting prey in leaf litter and loose soil before their single summer of flight. Autumn raking removes the habitat where most firefly populations overwinter.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Photuris_lucicrescens.jpg',
    photoCredit: 'Opoterser / CC BY-SA 3.0',
    page: 'fireflies',
    habitatTags: ['leaf-litter', 'tall-grass', 'edge'],
  },
  {
    id: 'box-turtle',
    name: 'Eastern Box Turtle',
    scientificName: 'Terrapene carolina',
    emoji: '🐢',
    shortDesc: 'Has a home range smaller than most suburban yards and navigates it from memory — the same log, the same berry patch, decade after decade. A single road crossing between two parts of its territory carries a measured mortality rate high enough to suppress local populations.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Eastern_Box_Turtle%2C_North_Carolina%2C_US_imported_from_iNaturalist_photo_71168521_%28cropped%29.jpg',
    photoCredit: 'tgosliner / iNaturalist, CC BY-NC 4.0',
    page: 'box-turtles',
    habitatTags: ['woodland', 'edge', 'leaf-litter'],
  },
  {
    id: 'native-bees',
    name: 'Native Bees',
    scientificName: '4,000+ species',
    emoji: '🐝',
    shortDesc: "Most of North America's 4,000+ native bee species are solitary ground nesters — females excavating individual tunnels in bare or sparsely vegetated soil. Continuous lawn coverage has eliminated most of their nesting habitat from the suburban landscape.",
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Bombus_lapidarius_-_Melilotus_officinalis_-_Tallinn.jpg',
    photoCredit: 'Iifar / CC BY-SA 3.0',
    page: 'native-bees',
    habitatTags: ['meadow', 'garden', 'bare-soil'],
  },
  {
    id: 'american-bumble-bee',
    name: 'American Bumble Bee',
    scientificName: 'Bombus pensylvanicus',
    emoji: '🐝',
    shortDesc: 'Once abundant across the eastern US, now absent from large portions of its range where it was documented as recently as the 1990s. A single queen founds each new colony in spring, overwintering alone underground after the entire colony dies each fall.',
    status: 'endangered',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Bombus_pensylvanicus_male_on_rough_blazingstar_Ellison_Creek-7907.jpg',
    photoCredit: 'USGS Bee Inventory and Monitoring Lab / CC BY 2.0',
    page: 'american-bumble-bee',
    habitatTags: ['meadow', 'garden', 'open-land'],
  },
  {
    id: 'spring-peeper',
    name: 'Northern Spring Peeper',
    scientificName: 'Pseudacris crucifer',
    emoji: '🐸',
    shortDesc: 'Weighs less than a gram. A group of 10 or 15 Spring Peepers calling from a vernal pool 50 yards away can be audible inside a house over traffic noise. Each individual call costs energy proportional to the frog\'s full body weight.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/H_crucifer_USGS.jpg',
    photoCredit: 'USGS / Public Domain',
    page: 'spring-peeper',
    habitatTags: ['wetland', 'vernal-pool', 'woodland-edge'],
  },
  {
    id: 'gray-treefrog',
    name: 'Eastern Gray Treefrog',
    scientificName: 'Hyla versicolor',
    emoji: '🐸',
    shortDesc: 'Can change its skin color from gray to green or brown over the course of minutes, matching the surface it rests on. A treefrog resting on gray bark in morning may shift to pale green by afternoon when it moves to a leaf.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Hyla_versicolor.jpg',
    photoCredit: 'Brian Gratwicke / CC BY 2.0',
    page: 'gray-tree-frogs',
    habitatTags: ['woodland-edge', 'garden', 'wetland-edge'],
  },
  {
    id: 'wood-frog',
    name: 'Wood Frog',
    scientificName: 'Lithobates sylvaticus',
    emoji: '🐸',
    shortDesc: 'Freezes solid in winter — heart stops, breathing stops, blood stops flowing — and thaws alive in spring. A frozen Wood Frog is indistinguishable from a dead one by every visible measure.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Rana_sylvatica.jpg',
    photoCredit: 'brian.gratwicke / CC BY 2.0',
    page: 'wood-frog',
    habitatTags: ['woodland', 'leaf-litter', 'vernal-pool'],
  },
  {
    id: 'american-toad',
    name: 'American Toad',
    scientificName: 'Anaxyrus americanus',
    emoji: '🐸',
    shortDesc: 'Eats up to 1,000 insects per day during active season. The parotoid glands behind its eyes secrete bufadienolides — compounds that cause cardiac arrhythmia in predators that mouth or swallow the toad.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Anaxyrus_americanus_PGC.jpg',
    photoCredit: 'PA Game Commission / Public Domain',
    page: 'toad',
    habitatTags: ['garden', 'woodland-edge', 'open-ground'],
  },
  {
    id: 'garter-snake',
    name: 'Eastern Garter Snake',
    scientificName: 'Thamnophis sirtalis',
    emoji: '🐍',
    shortDesc: 'Tolerates cold better than any other North American snake — active on days when air temperatures stay below 50°F, and among the last reptiles to hibernate in autumn. Females give birth to live young rather than eggs.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Thamnophis_sirtalis_sirtalis_Wooster.jpg',
    photoCredit: 'Ragesoss / CC BY-SA 3.0',
    page: 'garter-snake',
    habitatTags: ['garden', 'meadow', 'woodland-edge'],
  },
  {
    id: 'eastern-chipmunk',
    name: 'Eastern Chipmunk',
    scientificName: 'Tamias striatus',
    emoji: '🐿️',
    shortDesc: 'Stores up to 8,000 individual seeds in a single burrow, often arranged by species in separate chambers. Acorns buried and not retrieved account for a measurable share of oak regeneration in suburban forests.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Tamias_striatus2.jpg',
    photoCredit: 'Gilles Gonthier / CC BY 2.0',
    page: 'eastern-chipmunk',
    habitatTags: ['woodland-edge', 'garden', 'edge'],
  },
  {
    id: 'virginia-opossum',
    name: 'Virginia Opossum',
    scientificName: 'Didelphis virginiana',
    emoji: '🦔',
    shortDesc: "North America's only marsupial. Eats ticks at a rate measured in laboratory studies at roughly 5,500 per week — questing ticks that attach to the opossum are groomed off and consumed before they can feed.",
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/2/27/Didelphis_virginiana_with_young.jpg',
    photoCredit: 'Virginia State Parks staff / CC BY 2.0',
    page: 'virginia-opossum',
    habitatTags: ['woodland-edge', 'garden', 'suburban'],
  },
  {
    id: 'little-brown-bat',
    name: 'Little Brown Bat',
    scientificName: 'Myotis lucifugus',
    emoji: '🦇',
    shortDesc: 'Can eat its own body weight in insects on a single summer night. White-nose syndrome, a fungal disease introduced from Europe, has killed more than 6 million North American bats since 2006.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Little_brown_bat_28522.jpg',
    photoCredit: 'Ann Froschauer / USFWS / Public Domain',
    page: 'little-brown-bat',
    habitatTags: ['woodland-edge', 'wetland-edge', 'suburban'],
  },
  {
    id: 'downy-woodpecker',
    name: 'Downy Woodpecker',
    scientificName: 'Dryobates pubescens',
    emoji: '🐦',
    shortDesc: 'The smallest woodpecker in North America. Its bill is proportionally short — too short to reach the wood-boring beetle larvae that larger woodpeckers excavate. Instead it specializes in the larvae of stem-boring beetles and gall insects that larger species cannot access.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Downy_Woodpecker.jpg/500px-Downy_Woodpecker.jpg',
    photoCredit: 'Wolfgang Wander / CC BY-SA 3.0',
    page: 'downy-woodpecker',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'northern-flicker',
    name: 'Northern Flicker',
    scientificName: 'Colaptes auratus',
    emoji: '🐦',
    shortDesc: 'Forages almost entirely on the ground for ants, unlike other woodpeckers that work tree bark. Its tongue is barbed and coated in sticky saliva that captures ants in underground galleries. A single foraging bird extracts thousands of ants per session.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Northern_Flicker_%28Red-shafted%29.jpg',
    photoCredit: 'Elaine R. Wilson / CC BY-SA 2.5',
    page: 'northern-flicker',
    habitatTags: ['open-woodland', 'edge', 'lawn'],
  },
  {
    id: 'black-capped-chickadee',
    name: 'Black-capped Chickadee',
    scientificName: 'Poecile atricapillus',
    emoji: '🐦',
    shortDesc: 'Remembers the exact locations of thousands of individual food caches stored across hundreds of separate sites over periods of months. Studies measuring memory found the hippocampus grows measurably in autumn when caching peaks.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Black-capped_Chickadee_by_Dan_Pancamo_1.jpg/960px-Black-capped_Chickadee_by_Dan_Pancamo_1.jpg',
    photoCredit: 'Dan Pancamo / CC BY-SA 2.0',
    page: 'black-capped-chickadee',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'american-goldfinch',
    name: 'American Goldfinch',
    scientificName: 'Spinus tristis',
    emoji: '🐦',
    shortDesc: 'Waits until mid-summer to nest — later than almost any other songbird. The delay is timed to the peak seed production of native composites like coneflower and black-eyed Susan, which the adults need to feed their young.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Spinus-tristis-001.jpg',
    photoCredit: 'Mdf / CC BY-SA 3.0',
    page: 'american-goldfinch',
    habitatTags: ['meadow', 'garden', 'edge'],
  },
  {
    id: 'ruby-throated-hummingbird',
    name: 'Ruby-throated Hummingbird',
    scientificName: 'Archilochus colubris',
    emoji: '🐦',
    shortDesc: 'Crosses the Gulf of Mexico non-stop on a single fuel load — roughly 18–20 hours of flight over open water. Before the crossing, the bird doubles its body weight in fat accumulated over two weeks of intensive feeding.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Ruby_Throated_Hummingbird_%284702296458%29.jpg/960px-Ruby_Throated_Hummingbird_%284702296458%29.jpg',
    photoCredit: 'Mdf / CC BY-SA 3.0',
    page: 'ruby-throated-hummingbird',
    habitatTags: ['garden', 'woodland-edge', 'meadow'],
  },
  {
    id: 'american-robin',
    name: 'American Robin',
    scientificName: 'Turdus migratorius',
    emoji: '🐦',
    shortDesc: 'Detects earthworms partly by sound — cocking its head to listen for movement just below the soil surface. A robin pausing with one eye angled toward the ground is orienting its ear, not its eye, toward its prey.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Turdus-migratorius-002.jpg',
    photoCredit: 'Mdf / CC BY-SA 3.0',
    page: 'american-robin',
    habitatTags: ['garden', 'lawn', 'woodland-edge'],
  },
  {
    id: 'indigo-bunting',
    name: 'Indigo Bunting',
    scientificName: 'Passerina cyanea',
    emoji: '🐦',
    shortDesc: 'The male\'s blue color comes entirely from light scattering — there is no blue pigment in the feathers. The same feather that appears intense blue in direct sun appears black in shade. The bird navigates at night using star patterns it memorized as a nestling.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Indigo_Bunting_by_Dan_Pancamo.jpg',
    photoCredit: 'Dan Pancamo / CC BY-SA 2.0',
    page: 'indigo-bunting',
    habitatTags: ['edge', 'meadow', 'garden'],
  },
  {
    id: 'baltimore-oriole',
    name: 'Baltimore Oriole',
    scientificName: 'Icterus galbula',
    emoji: '🐦',
    shortDesc: 'Builds a pendant nest that hangs from the tip of a branch — woven from plant fibers, bark strips, and hair so tightly that it holds its shape against wind without being attached along its sides. Construction takes four to eight days.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Baltimore_Oriole-_dorsum.jpg',
    photoCredit: 'Alan D. Wilson / CC BY-SA 3.0',
    page: 'baltimore-oriole',
    habitatTags: ['open-woodland', 'edge', 'garden'],
  },
  {
    id: 'northern-cardinal',
    name: 'Northern Cardinal',
    scientificName: 'Cardinalis cardinalis',
    emoji: '🐦',
    shortDesc: 'One of the few North American songbirds where the female sings. Female cardinals sing back-and-forth with their mates during nesting — exchanging calls while the female sits on the eggs and the male forages.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Northern_Cardinal_male_%28cropped%29.jpg',
    photoCredit: 'skeeze / CC0 1.0',
    page: 'northern-cardinal',
    habitatTags: ['woodland-edge', 'garden', 'shrub'],
  },
  {
    id: 'northern-mockingbird',
    name: 'Northern Mockingbird',
    scientificName: 'Mimus polyglottos',
    emoji: '🐦',
    shortDesc: 'Can produce over 200 distinct song types and continues adding new ones throughout its life. Males who have lived longer and accumulated more song types attract more mates — the repertoire is a direct measure of age and survival.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Mimus_polyglottos_Adult_10.jpg',
    photoCredit: 'Manjith Kainickara / CC BY-SA 2.0',
    page: 'northern-mockingbird',
    habitatTags: ['garden', 'open-ground', 'edge'],
  },
  {
    id: 'eastern-bluebird',
    name: 'Eastern Bluebird',
    scientificName: 'Sialia sialis',
    emoji: '🐦',
    shortDesc: 'Declined from common to rare across much of the eastern US between 1930 and 1980 as European Starlings and House Sparrows occupied the nest cavities bluebirds require. The population recovery after nest box programs began is one of the most documented cases of direct human intervention reversing a songbird decline.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Eastern_bluebird_pair.jpg',
    photoCredit: 'Sandysphotos2009 / CC BY 2.0',
    page: 'eastern-bluebird',
    habitatTags: ['open-woodland', 'edge', 'meadow'],
  },
  {
    id: 'dark-eyed-junco',
    name: 'Dark-eyed Junco',
    scientificName: 'Junco hyemalis',
    emoji: '🐦',
    shortDesc: 'The most abundant winter bird in North America by some estimates — around 630 million individuals move south each fall. A junco seen at a feeder in January was born in a boreal forest or mountain range and will leave again in March.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Dark_Eyed_Junco.jpg',
    photoCredit: 'John Harrison / CC BY-SA 3.0',
    page: 'dark-eyed-junco',
    habitatTags: ['woodland-edge', 'garden', 'ground-cover'],
  },
  {
    id: 'american-tree-sparrow',
    name: 'American Tree Sparrow',
    scientificName: 'Spizelloides arborea',
    emoji: '🐦',
    shortDesc: 'Breeds above the tree line in Arctic tundra and spends winters foraging on seeds in snow-covered fields. Counts at winter feeding stations have declined measurably in parallel with warming winters, suggesting the species is shifting its range northward.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/American_Tree_Sparrow-27527-2.jpg',
    photoCredit: 'Fyn Kynd / CC BY 2.0',
    page: 'american-tree-sparrow',
    habitatTags: ['field', 'edge', 'garden'],
  },
  {
    id: 'wood-thrush',
    name: 'Wood Thrush',
    scientificName: 'Hylocichla mustelina',
    emoji: '🐦',
    shortDesc: 'Can produce two notes simultaneously — its syrinx has two sides that operate independently, allowing it to harmonize with itself. The song is audible from 200 meters through dense forest.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Hylocichla_mustelina_-_Wood_Thrush.jpg',
    photoCredit: 'John Harrison / CC BY-SA 3.0',
    page: 'wood-thrush',
    habitatTags: ['forest-interior', 'woodland', 'leaf-litter'],
  },
  {
    id: 'eastern-screech-owl',
    name: 'Eastern Screech-Owl',
    scientificName: 'Megascops asio',
    emoji: '🦉',
    shortDesc: 'Roosts in tree cavities and nest boxes during the day, often visible at the entrance hole in late afternoon. A screech-owl raising young in a nest box consumes roughly 150–200 prey items per brood — mostly large insects, small rodents, and earthworms.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Eastern_Screech_Owl_%28Megascops_asio%29.jpg',
    photoCredit: 'OZinOH / CC BY-NC 2.0',
    page: 'eastern-screech-owl',
    habitatTags: ['woodland', 'edge', 'suburban'],
  },
  {
    id: 'red-tailed-hawk',
    name: 'Red-tailed Hawk',
    scientificName: 'Buteo jamaicensis',
    emoji: '🦅',
    shortDesc: 'The most common large hawk in North America. Pairs return to the same nest territory year after year, refurbishing the same nest structure with new material each season — some nest platforms are used for decades.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Red-tailed_Hawk_%2835666104861%29.jpg',
    photoCredit: 'Andy Morffew / CC BY 2.0',
    page: 'red-tailed-hawk',
    habitatTags: ['open-land', 'edge', 'woodland'],
  },
  {
    id: 'american-kestrel',
    name: 'American Kestrel',
    scientificName: 'Falco sparverius',
    emoji: '🦅',
    shortDesc: 'The smallest falcon in North America. Can see ultraviolet light, which allows it to follow the urine trails of small rodents — trails that are invisible to humans but reflect UV and lead directly to runways and burrow entrances.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/American_Kestrel_%28Male%29.jpg/960px-American_Kestrel_%28Male%29.jpg',
    photoCredit: 'Mdf / CC BY-SA 3.0',
    page: 'american-kestrel',
    habitatTags: ['open-land', 'meadow', 'edge'],
  },
  {
    id: 'eastern-meadowlark',
    name: 'Eastern Meadowlark',
    scientificName: 'Sturnella magna',
    emoji: '🐦',
    shortDesc: 'Has lost over 75% of its North American population since 1970. Its nest is built as a dome of grasses with a side entrance tunnel — invisible from above and requiring uncut grassland of at least several acres for nesting to succeed.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Sturnella_magna_-_Eastern_Meadowlark_XL.jpg',
    photoCredit: 'Dick Daniels / CC BY-SA 3.0',
    page: 'eastern-meadowlark',
    habitatTags: ['open-meadow', 'grassland', 'field'],
  },
  {
    id: 'chimney-swift',
    name: 'Chimney Swift',
    scientificName: 'Chaetura pelagica',
    emoji: '🐦',
    shortDesc: 'Cannot perch — its feet grip vertical surfaces only. It eats, drinks, mates, and collects nesting material entirely in flight. A swift that lands on a flat surface cannot take off again.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Chaetura_pelagica_-_chimney_swift.JPG',
    photoCredit: 'Googie man / CC BY-SA 3.0',
    page: 'chimney-swift',
    habitatTags: ['aerial', 'urban', 'suburban'],
  },
  {
    id: 'common-nighthawk',
    name: 'Common Nighthawk',
    scientificName: 'Chordeiles minor',
    emoji: '🐦',
    shortDesc: 'Hatches two eggs on bare gravel rooftops or open ground with no nest material. The female rotates the eggs to maintain even temperature, then shades them from direct sun with her body when temperatures rise.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Common_Nighthawk_%28Chordeiles_minor%29_%28cropped%29.jpg',
    photoCredit: 'Frank Schulenburg / CC BY-SA 4.0',
    page: 'common-nighthawk',
    habitatTags: ['aerial', 'open-ground', 'rooftop'],
  },
  {
    id: 'purple-martin',
    name: 'Purple Martin',
    scientificName: 'Progne subis',
    emoji: '🐦',
    shortDesc: 'In eastern North America, the entire breeding population now nests almost exclusively in human-provided housing. The birds that pioneered this shift produced offspring that returned to the same housing type, accelerating the switch until wild cavity nesting became rare.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Progne_subis_-_male.jpg',
    photoCredit: 'Mdf / CC BY-SA 3.0',
    page: 'purple-martin',
    habitatTags: ['aerial', 'open-water', 'suburban'],
  },
  {
    id: 'brown-thrasher',
    name: 'Brown Thrasher',
    scientificName: 'Toxostoma rufum',
    emoji: '🐦',
    shortDesc: 'Has the largest documented song repertoire of any North American bird — over 1,100 distinct song types. Males sing each phrase twice before moving to the next, a rhythm that distinguishes thrashers from mockingbirds, which repeat phrases three or more times.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Brown_Thrasher_%28Toxostoma_rufum%29_%28Cropped%29.jpg',
    photoCredit: 'Dan Pancamo / CC BY-SA 2.0',
    page: 'brown-thrasher',
    habitatTags: ['shrub', 'edge', 'woodland-edge'],
  },
  {
    id: 'eastern-towhee',
    name: 'Eastern Towhee',
    scientificName: 'Pipilo erythrophthalmus',
    emoji: '🐦',
    shortDesc: 'Forages by backward-scratching — jumping forward and raking both feet back through leaf litter simultaneously to expose seeds and insects beneath. The motion is audible from several feet away.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Pipilo_erythrophthalmus_%28Eastern_Towhee%29.jpg',
    photoCredit: 'Steve Maslowski / USFWS / Public Domain',
    page: 'eastern-towhee',
    habitatTags: ['shrub', 'edge', 'leaf-litter'],
  },
  {
    id: 'gray-catbird',
    name: 'Gray Catbird',
    scientificName: 'Dumetella carolinensis',
    emoji: '🐦',
    shortDesc: 'Recognizes and ejects Brown-headed Cowbird eggs from its nest at a higher rate than most other species — an evolved response to a parasite that has been part of its range for many generations. Can mimic dozens of other bird species, but rarely repeats the same phrase more than once.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Gray_Catbird_%28Dumetella_carolinensis%29.jpg',
    photoCredit: 'Kelly Colgan Azar / CC BY-ND 2.0',
    page: 'gray-catbird',
    habitatTags: ['shrub', 'edge', 'garden'],
  },
  {
    id: 'carolina-wren',
    name: 'Carolina Wren',
    scientificName: 'Thryothorus ludovicianus',
    emoji: '🐦',
    shortDesc: 'One of the loudest birds in North America relative to body size. Produces 27–40 distinct song types and countersings with neighbors — one bird begins a phrase, a nearby male immediately responds with the same type, the exchange continuing back and forth.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Thryothorus_ludovicianus_-_Carolina_Wren.jpg',
    photoCredit: 'Ken Thomas / Public Domain',
    page: 'carolina-wren',
    habitatTags: ['woodland-edge', 'shrub', 'garden'],
  },
  {
    id: 'mourning-dove',
    name: 'Mourning Dove',
    scientificName: 'Zenaida macroura',
    emoji: '🐦',
    shortDesc: 'Can fly at 55 mph and produces a distinctive wing whistle from specialized primary feathers that sounds on takeoff — thought to function as an alarm. A disturbed flock leaves simultaneously, the whistle amplified by multiple birds taking flight at once.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Zenaida_macroura_-_Mourning_Dove_-_XL.jpg',
    photoCredit: 'Dick Daniels / CC BY-SA 3.0',
    page: 'mourning-dove',
    habitatTags: ['garden', 'open-ground', 'edge'],
  },
  {
    id: 'song-sparrow',
    name: 'Song Sparrow',
    scientificName: 'Melospiza melodia',
    emoji: '🐦',
    shortDesc: 'One of the most studied birds in North America. Males learn their songs from neighboring males during their first year, then keep that repertoire for life — so neighboring males in a territory often share songs, while males from separate areas do not.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Melospiza_melodia_-Lac_la_Biche%2C_Alberta%2C_Canada-8.jpg',
    photoCredit: 'dfaulder / CC BY 2.0',
    page: 'song-sparrow',
    habitatTags: ['shrub', 'edge', 'wetland-edge'],
  },
  {
    id: 'yellow-rumped-warbler',
    name: 'Yellow-rumped Warbler',
    scientificName: 'Setophaga coronata',
    emoji: '🐦',
    shortDesc: 'One of the few warblers that can digest the waxy coating on bayberry and wax myrtle berries. This allows it to winter farther north than almost any other warbler, subsisting on fruit when insects are unavailable.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Yellow-rumped_Warbler.jpg',
    photoCredit: 'DickDaniels / CC BY-SA 3.0',
    page: 'yellow-rumped-warbler',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'wild-turkey',
    name: 'Wild Turkey',
    scientificName: 'Meleagris gallopavo',
    emoji: '🦃',
    shortDesc: 'Was eliminated from most of the eastern US by 1900. Reintroduced in 49 states using birds trapped in remnant populations in the Appalachians — one of the most successful wildlife restoration programs in American history, driven almost entirely by wild-stock translocation rather than captive breeding.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Wild_turkey_eastern_US.jpg',
    photoCredit: 'John J. Audubon / Public Domain',
    page: 'wild-turkey',
    habitatTags: ['woodland-edge', 'open-land', 'meadow'],
  },
  {
    id: 'eastern-phoebe',
    name: 'Eastern Phoebe',
    scientificName: 'Sayornis phoebe',
    emoji: '🐦',
    shortDesc: 'One of the first songbirds studied with banding in North America — John James Audubon tied silver thread to the legs of nestlings in 1804 and confirmed the next year that the same birds returned to nest in the same location.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Eastern_Phoebe-27527.jpg',
    photoCredit: 'Fyn Kynd Photography / CC BY 2.0',
    page: 'eastern-phoebe',
    habitatTags: ['woodland-edge', 'water-edge', 'suburban'],
  },
  {
    id: 'yellow-warbler',
    name: 'Yellow Warbler',
    scientificName: 'Setophaga petechia',
    emoji: '🐦',
    shortDesc: "When a Brown-headed Cowbird lays an egg in its nest, the Yellow Warbler often detects it and builds a new floor over the entire clutch — burying both its own eggs and the cowbird's egg rather than raising the parasite. Some nests show up to six floor layers from repeated parasitism events.",
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Yellow_Warbler_%28male%29.jpg',
    photoCredit: 'Steve Maslowski / USFWS / Public Domain',
    page: 'yellow-warbler',
    habitatTags: ['shrub', 'wetland-edge', 'edge'],
  },
  {
    id: 'ruby-crowned-kinglet',
    name: 'Ruby-crowned Kinglet',
    scientificName: 'Corthylio calendula',
    emoji: '🐦',
    shortDesc: "One of North America's smallest songbirds — weighs about as much as a dime. Lays clutches of up to 12 eggs, the largest clutch-to-body-size ratio of any North American bird. A clutch of 12 eggs weighs more than the female's own body.",
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Ruby_Crowned_Kinglet_%2826541105131%29.jpg',
    photoCredit: 'Andy Morffew / CC BY 2.0',
    page: 'ruby-crowned-kinglet',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'cedar-waxwing',
    name: 'Cedar Waxwing',
    scientificName: 'Bombycilla cedrorum',
    emoji: '🐦',
    shortDesc: "One of the few North American birds that can survive on fruit alone for months. Flocks locate ripe berries by sight and exhaust the supply before moving to the next patch — a nomadic behavior driven entirely by fruit availability rather than fixed territory.",
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Cedar_Waxwing_-_Bombycilla_cedrorum_%2814334573026%29.jpg',
    photoCredit: 'Francesco Veronesi / CC BY-SA 2.0',
    page: 'cedar-waxwing',
    habitatTags: ['woodland-edge', 'garden', 'open-woodland'],
  },
  {
    id: 'scarlet-tanager',
    name: 'Scarlet Tanager',
    scientificName: 'Piranga olivacea',
    emoji: '🐦',
    shortDesc: 'Requires large tracts of intact forest interior — populations crash in forests fragmented into patches smaller than about 250 acres. The male\'s scarlet and black plumage is produced by carotenoid pigments derived entirely from diet.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Piranga_olivacea_-_Scarlet_Tanager_%28male%29_1.jpg',
    photoCredit: 'Mdf / CC BY-SA 3.0',
    page: 'scarlet-tanager',
    habitatTags: ['forest-interior', 'woodland', 'canopy'],
  },
  {
    id: 'whip-poor-will',
    name: 'Eastern Whip-poor-will',
    scientificName: 'Antrostomus vociferus',
    emoji: '🐦',
    shortDesc: 'Lays eggs on the forest floor with no nest — eggs and chicks are camouflaged as dead leaves. Times breeding to the full moon so there is enough light to catch moths at night during the chicks\' peak feeding period.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Antrostomus_vociferus_NPS.jpg',
    photoCredit: 'NPS / Public Domain',
    page: 'whip-poor-will',
    habitatTags: ['woodland', 'edge', 'open-woodland'],
  },
  {
    id: 'ovenbird',
    name: 'Ovenbird',
    scientificName: 'Seiurus aurocapilla',
    emoji: '🐦',
    shortDesc: 'Builds a domed nest on the forest floor that looks like a Dutch oven — hence the name. Walks rather than hops when foraging among leaf litter, and requires large blocks of contiguous forest; fragmentation drops breeding success sharply.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Seiurus_aurocapilla_-Hopewell_NJ_USA-8.jpg',
    photoCredit: 'Dori / CC BY-SA 3.0',
    page: 'ovenbird',
    habitatTags: ['forest-interior', 'woodland', 'leaf-litter'],
  },
  {
    id: 'brown-creeper',
    name: 'Brown Creeper',
    scientificName: 'Certhia americana',
    emoji: '🐦',
    shortDesc: 'Forages by spiraling up one tree trunk, then flying to the base of the next tree and spiraling up again — never downward. The curved bill is shaped to extract insect eggs and pupae from crevices in rough bark.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Brown_Creeper.jpg',
    photoCredit: 'Rick Leche / CC BY 2.0',
    page: 'brown-creeper',
    habitatTags: ['woodland', 'bark', 'canopy'],
  },
  {
    id: 'hermit-thrush',
    name: 'Hermit Thrush',
    scientificName: 'Catharus guttatus',
    emoji: '🐦',
    shortDesc: 'The only spotted thrush that winters in the US. Its song was described by Whitman as "spiritual, wondrous" — but what is measurable about it is the structure: the bird sings each phrase at a different pitch from the one before, creating a sequence that never directly repeats.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Catharus_guttatus_3.jpg',
    photoCredit: 'Manjith Kainickara / CC BY-SA 2.0',
    page: 'hermit-thrush',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'eastern-wood-pewee',
    name: 'Eastern Wood-Pewee',
    scientificName: 'Contopus virens',
    emoji: '🐦',
    shortDesc: 'Population has declined about 1% per year for four decades — a total loss exceeding 35% since 1970. Nests late in the season, building a shallow cup camouflaged with lichen on a horizontal branch. The nest is nearly invisible from below.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Eastern_Wood-Pewee.jpg',
    photoCredit: 'Ken Thomas / Public Domain',
    page: 'eastern-wood-pewee',
    habitatTags: ['woodland', 'canopy', 'edge'],
  },
  {
    id: 'polyphemus-moth',
    name: 'Polyphemus Moth',
    scientificName: 'Antheraea polyphemus',
    emoji: '🦋',
    shortDesc: 'One of the largest moths in North America. Adults have no functional mouths — they cannot eat. The adult moth lives entirely on fat reserves accumulated during the caterpillar stage and dies within days of mating.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Antheraea_polyphemus.jpg',
    photoCredit: 'Smokeybjb / CC BY-SA 3.0',
    page: 'polyphemus-moth',
    habitatTags: ['woodland', 'garden', 'edge'],
  },
  {
    id: 'luna-moth',
    name: 'Luna Moth',
    scientificName: 'Actias luna',
    emoji: '🦋',
    shortDesc: 'The hindwing tails are long enough that a bat\'s echolocation returns a false signal — the moth\'s body registers as smaller and farther away than it actually is. Bats miss a detectable fraction of attacks on tailed moths.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Actias_luna_MHNT.jpg',
    photoCredit: 'Didier Descouens / CC BY-SA 4.0',
    page: 'luna-moth',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'cecropia-moth',
    name: 'Cecropia Moth',
    scientificName: 'Hyalophora cecropia',
    emoji: '🦋',
    shortDesc: 'North America\'s largest native moth — wingspan up to 6 inches. Like the Polyphemus and Luna, adults have non-functional mouths and live only long enough to mate. The female releases pheromones after midnight; males can detect them from a mile away.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Hyalophora_cecropia_male.jpg',
    photoCredit: 'Sarefo / CC BY-SA 3.0',
    page: 'cecropia-moth',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'hummingbird-clearwing-moth',
    name: 'Hummingbird Clearwing Moth',
    scientificName: 'Hemaris thysbe',
    emoji: '🦋',
    shortDesc: 'Hovers at flowers and extends its proboscis to reach nectar — behavior so similar to a hummingbird that many observers do not realize it is an insect. Wing scales are shed on the first flight, leaving clear windows in the wing.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Hemaris_thysbe_1.jpg/960px-Hemaris_thysbe_1.jpg',
    photoCredit: 'Didier Descouens / CC BY-SA 4.0',
    page: 'hummingbird-clearwing-moth',
    habitatTags: ['garden', 'edge', 'meadow'],
  },
  {
    id: 'green-darner',
    name: 'Green Darner',
    scientificName: 'Anax junius',
    emoji: '🐛',
    shortDesc: 'Migrates thousands of miles in autumn — one of only a few dragonfly species known to migrate. Individuals tracked with radio transmitters traveled up to 100 miles per day, following cold fronts south much like songbird migrants.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Anax_junius.jpg',
    photoCredit: 'Gilles San Martin / CC BY-SA 2.0',
    page: 'green-darner',
    habitatTags: ['wetland', 'pond', 'meadow'],
  },
  {
    id: 'tiger-swallowtail',
    name: 'Eastern Tiger Swallowtail',
    scientificName: 'Papilio glaucus',
    emoji: '🦋',
    shortDesc: 'The most widespread swallowtail in eastern North America. Females produce two very different forms: yellow-patterned like the male, or nearly black — the dark form mimics the Pipevine Swallowtail, which is distasteful to birds.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Papilio_glaucus.jpg/960px-Papilio_glaucus.jpg',
    photoCredit: 'Didier Descouens / CC BY-SA 4.0',
    page: 'tiger-swallowtail',
    habitatTags: ['woodland-edge', 'garden', 'meadow'],
  },
  {
    id: 'black-swallowtail',
    name: 'Black Swallowtail',
    scientificName: 'Papilio polyxenes',
    emoji: '🦋',
    shortDesc: 'Its caterpillar feeds exclusively on plants in the carrot family — parsley, dill, fennel, Queen Anne\'s lace. The caterpillar carries a forked orange organ behind its head called an osmeterium that releases a foul odor when the caterpillar is disturbed.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Papilio_polyxenes_-_female.jpg',
    photoCredit: 'Bob Peterson / CC BY-SA 2.0',
    page: 'black-swallowtail',
    habitatTags: ['garden', 'meadow', 'open-land'],
  },
  {
    id: 'spicebush-swallowtail',
    name: 'Spicebush Swallowtail',
    scientificName: 'Papilio troilus',
    emoji: '🦋',
    shortDesc: 'Its caterpillar folds a leaf in half and lives inside the fold — sealing the edges with silk to create a shelter it retreats into when not feeding. The caterpillar has two large eyespots on its thorax that resemble a snake\'s head when the leaf shelter is opened.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Spicebush_Swallowtail_Butterfly_%28Papilio_troilus%29_%285087430553%29.jpg',
    photoCredit: 'Donald Hobern / CC BY 2.0',
    page: 'spicebush-swallowtail',
    habitatTags: ['woodland-edge', 'garden', 'spicebush'],
  },
  {
    id: 'giant-swallowtail',
    name: 'Giant Swallowtail',
    scientificName: 'Papilio cresphontes',
    emoji: '🦋',
    shortDesc: 'The largest butterfly in North America by wingspan. Its caterpillar resembles a fresh bird dropping — brown, shiny, and irregular — well enough to deter most visual predators. The caterpillar feeds on plants in the citrus family, including Hop Tree and Wafer Ash.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Papilio_cresphontes1.jpg',
    photoCredit: 'Bob Peterson / CC BY 2.0',
    page: 'giant-swallowtail',
    habitatTags: ['woodland-edge', 'garden', 'hop-tree'],
  },
  {
    id: 'great-spangled-fritillary',
    name: 'Great Spangled Fritillary',
    scientificName: 'Speyeria cybele',
    emoji: '🦋',
    shortDesc: 'Lays eggs not on violet plants directly but on dead leaf litter near them. The newly hatched caterpillar must find the violet itself without any parent guidance — it overwinters as a first-instar larva without eating, then locates a violet in spring.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Great_Spangled_Fritillary.jpg',
    photoCredit: 'Thomas Shahan / CC BY 2.0',
    page: 'great-spangled-fritillary',
    habitatTags: ['meadow', 'woodland-edge', 'violet-patch'],
  },
  {
    id: 'pearl-crescent',
    name: 'Pearl Crescent',
    scientificName: 'Phyciodes tharos',
    emoji: '🦋',
    shortDesc: 'One of the most common butterflies in eastern North America. Its caterpillar feeds exclusively on native asters — and the loss of native asters from suburban lawns has measurably reduced Pearl Crescent abundance in areas where non-native grass monocultures replaced mixed meadow.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Phyciodes_tharos_Pearl_Crescent.jpg',
    photoCredit: 'Quartl / CC BY-SA 3.0',
    page: 'pearl-crescent',
    habitatTags: ['meadow', 'garden', 'edge'],
  },
  {
    id: 'red-admiral',
    name: 'Red Admiral',
    scientificName: 'Vanessa atalanta',
    emoji: '🦋',
    shortDesc: 'Its caterpillar feeds almost exclusively on nettles — a plant most gardeners remove on sight. The adult male establishes a territory and returns to the same perch repeatedly over several days, defending it against other butterflies.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/RedAdmiralButterfly.jpg',
    photoCredit: 'Andy Reago & Chrissy McClarren / CC BY 2.0',
    page: 'red-admiral',
    habitatTags: ['nettle-patch', 'woodland-edge', 'garden'],
  },
  {
    id: 'painted-lady',
    name: 'Painted Lady',
    scientificName: 'Vanessa cardui',
    emoji: '🦋',
    shortDesc: 'The most widely distributed butterfly in the world — found on every continent except Antarctica and Australia. Migrates in cyclic population explosions tied to rainfall in its North African breeding grounds that produce massive thistle crops; waves of migrants reach the UK from Africa in years when the cycle peaks.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Vanessa_cardui_DSC_0001.jpg',
    photoCredit: 'Quartl / CC BY-SA 3.0',
    page: 'painted-lady',
    habitatTags: ['meadow', 'garden', 'open-land'],
  },
  {
    id: 'mourning-cloak',
    name: 'Mourning Cloak',
    scientificName: 'Nymphalis antiopa',
    emoji: '🦋',
    shortDesc: 'One of the longest-lived adult butterflies in North America — adults can survive nine to ten months. Overwinters as an adult rather than as a chrysalis, sheltering in tree cavities and under bark. On warm days in February, adults are sometimes the first butterflies seen of the year.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Nymphalis_antiopa_DSC_0001.jpg',
    photoCredit: 'Quartl / CC BY-SA 3.0',
    page: 'mourning-cloak',
    habitatTags: ['woodland', 'edge', 'garden'],
  },
  {
    id: 'question-mark',
    name: 'Question Mark',
    scientificName: 'Polygonia interrogationis',
    emoji: '🦋',
    shortDesc: 'Named for a small silvery mark on the underside of its hindwing — a curved line and a separate dot that together form a punctuation mark. Overwinters as an adult and feeds on rotting fruit, tree sap, and carrion rather than flowers.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Question_Mark_Butterfly_%28Polygonia_interrogationis%29.jpg',
    photoCredit: 'Judy Gallagher / CC BY 2.0',
    page: 'question-mark',
    habitatTags: ['woodland-edge', 'elm', 'garden'],
  },
  {
    id: 'eastern-comma',
    name: 'Eastern Comma',
    scientificName: 'Polygonia comma',
    emoji: '🦋',
    shortDesc: 'Named for the same reason as the Question Mark — a small silver mark on the hindwing underside, this one shaped like a comma. Produces two annual forms: a pale summer form and a darker winter form that overwinters as an adult.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/334405655/large.jpg',
    photoCredit: 'Jayce Swalve / CC BY-NC via iNaturalist',
    page: 'eastern-comma',
    habitatTags: ['woodland-edge', 'hop-sedge', 'garden'],
  },
  {
    id: 'viceroy',
    name: 'Viceroy',
    scientificName: 'Limenitis archippus',
    emoji: '🦋',
    shortDesc: 'Long used as the textbook example of Batesian mimicry — a palatable species copying the appearance of an unpalatable one. Research in the 1990s found that Viceroys are themselves unpalatable due to salicylate compounds from their willow host plants, making it a case of Müllerian mimicry instead.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Limenitis_archippus_Cramer.jpg',
    photoCredit: 'Didier Descouens / CC BY-SA 4.0',
    page: 'viceroy',
    habitatTags: ['wetland-edge', 'willow', 'meadow'],
  },
  {
    id: 'american-lady',
    name: 'American Lady',
    scientificName: 'Vanessa virginiensis',
    emoji: '🦋',
    shortDesc: 'Distinguished from the Painted Lady by two large eyespots on its hindwing underside — the Painted Lady has four smaller ones. Caterpillars feed on plants in the everlasting family (Gnaphalium, Antennaria) and build silk shelters by tying leaves together.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/American_Lady_%28Vanessa_virginiensis%29_%2814543668427%29.jpg',
    photoCredit: 'Andy Reago & Chrissy McClarren / CC BY 2.0',
    page: 'american-lady',
    habitatTags: ['meadow', 'garden', 'open-land'],
  },
  {
    id: 'common-buckeye',
    name: 'Common Buckeye',
    scientificName: 'Junonia coenia',
    emoji: '🦋',
    shortDesc: 'The large eyespots on its wings function as a startle display — a predator that strikes at a wing eyespot misses the body. The Buckeye cannot overwinter in cold climates; every individual seen north of Virginia in summer is a migrant or the descendant of one.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Junonia_coenia_-_Buckeye_Butterfly_-_Florida.jpg',
    photoCredit: 'Judy Gallagher / CC BY 2.0',
    page: 'common-buckeye',
    habitatTags: ['open-ground', 'meadow', 'garden'],
  },
  {
    id: 'baltimore-checkerspot',
    name: 'Baltimore Checkerspot',
    scientificName: 'Euphydryas phaeton',
    emoji: '🦋',
    shortDesc: 'One of the few butterflies that requires a specific caterpillar host in a specific habitat: White Turtlehead growing in wet meadows and stream edges. Development is tightly timed — caterpillars must reach a certain size before winter or they do not survive diapause.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Euphydryas_phaeton_-_Baltimore_Checkerspot.jpg',
    photoCredit: 'Rob Curtis / CC BY-SA 4.0',
    page: 'baltimore-checkerspot',
    habitatTags: ['wetland-edge', 'turtlehead', 'meadow'],
  },
  {
    id: 'silvery-checkerspot',
    name: 'Silvery Checkerspot',
    scientificName: 'Chlosyne nycteis',
    emoji: '🦋',
    shortDesc: 'Caterpillars are gregarious in early instars — hatching together and feeding in groups on the same sunflower or Black-eyed Susan plant before dispersing to feed alone. The larval cluster is visible as a patch of skeletonized leaves.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Chlosyne_nycteis_-_Silvery_Checkerspot.jpg',
    photoCredit: 'Judy Gallagher / CC BY 2.0',
    page: 'silvery-checkerspot',
    habitatTags: ['meadow', 'garden', 'open-land'],
  },
  {
    id: 'cloudless-sulphur',
    name: 'Cloudless Sulphur',
    scientificName: 'Phoebis sennae',
    emoji: '🦋',
    shortDesc: 'Large, fast-flying, and hard to confuse in the field — males are solid lemon yellow, one of the most saturated yellows of any North American butterfly. Its caterpillar changes color depending on what part of the Wild Senna plant it is eating — green on new growth, yellow on flowers.',
    status: 'stable',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Cloudless_Sulphur_Butterfly_%28Phoebis_sennae%29_Pollinating_-_Grill%2C_SC_USA.jpg/960px-Cloudless_Sulphur_Butterfly_%28Phoebis_sennae%29_Pollinating_-_Grill%2C_SC_USA.jpg',
    photoCredit: 'Rhododendrites / CC BY-SA 4.0',
    page: 'cloudless-sulphur',
    habitatTags: ['legume-garden', 'open-meadow', 'woodland-edge'],
  },
  {
    id: 'cabbage-white',
    name: 'Cabbage White',
    scientificName: 'Pieris rapae',
    emoji: '🦋',
    shortDesc: 'Arrived in Quebec from Europe around 1860 and spread to California within forty years — one of the fastest documented range expansions of any introduced insect. It displaced the native Checkered White from most of its eastern range.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Pieris_rapae_qtl2.jpg',
    photoCredit: 'Quartl / CC BY-SA 3.0',
    page: 'cabbage-white',
    habitatTags: ['garden', 'open-land', 'meadow'],
  },
  {
    id: 'west-virginia-white',
    name: 'West Virginia White',
    scientificName: 'Pieris virginiensis',
    emoji: '🦋',
    shortDesc: 'Found only in intact interior forest — it does not fly across open clearings or gaps. Its caterpillar feeds on native toothworts (Cardamine), and the butterfly is now gone from many forests where garlic mustard has replaced those toothworts.',
    status: 'declining',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/89049558/large.jpg',
    photoCredit: 'tomgatz / CC BY-NC via iNaturalist',
    page: 'west-virginia-white',
    habitatTags: ['forest-interior', 'woodland', 'toothwort'],
  },
  {
    id: 'spring-azure',
    name: 'Spring Azure',
    scientificName: 'Celastrina ladon',
    emoji: '🦋',
    shortDesc: 'One of the first butterflies to emerge in spring — adults fly when temperatures are still below 50°F on warm afternoons. Males are solid pale blue; females have black borders on the forewing. The caterpillar feeds on flower buds rather than leaves.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/4777454/large.jpg',
    photoCredit: 'Don Loarie / CC BY via iNaturalist',
    page: 'spring-azure',
    habitatTags: ['woodland-edge', 'shrub', 'garden'],
  },
  {
    id: 'olympia-marble',
    name: 'Olympia Marble',
    scientificName: 'Euchloe olympia',
    emoji: '🦋',
    shortDesc: 'Flies for only four to six weeks in spring — entirely gone by late May. Its caterpillar feeds on native mustard-family plants including rock cress and bitter cress. The Olympia Marble requires open, rocky, or sandy prairie remnants and does not persist in closed-canopy forest or lawn.',
    status: 'declining',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/121584905/large.jpg',
    photoCredit: 'amyandthecats / CC BY-NC via iNaturalist',
    page: 'olympia-marble',
    habitatTags: ['dry-prairie', 'open-ground', 'rock-cress'],
  },
  {
    id: 'orange-sulphur',
    name: 'Orange Sulphur',
    scientificName: 'Colias eurytheme',
    emoji: '🦋',
    shortDesc: 'One of the most abundant butterflies in eastern North America. Its caterpillar feeds on alfalfa and native clovers — agricultural expansion in the 20th century dramatically increased its range and numbers. Now interbreeds extensively with the Clouded Sulphur where the two co-occur.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/109888994/large.jpeg',
    photoCredit: 'Greg Lasley / CC BY-NC via iNaturalist',
    page: 'orange-sulphur',
    habitatTags: ['meadow', 'clover-field', 'open-land'],
  },
  {
    id: 'clouded-sulphur',
    name: 'Clouded Sulphur',
    scientificName: 'Colias philodice',
    emoji: '🦋',
    shortDesc: 'Females produce two distinct color forms: yellow (like the male) and white. The white form is found in the same populations as the yellow form — the two are not separate species or populations, and both can occur in the same brood.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/102453266/large.jpeg',
    photoCredit: 'Eric Isley / CC BY-NC via iNaturalist',
    page: 'clouded-sulphur',
    habitatTags: ['meadow', 'clover-field', 'open-land'],
  },
  {
    id: 'checkered-white',
    name: 'Checkered White',
    scientificName: 'Pontia protodice',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/655817929/large.jpg',
    photoCredit: 'Kristin Sweeney / CC BY-NC via iNaturalist',
    page: 'checkered-white' as Page,
    status: 'declining' as const,
    habitatTags: ['open-ground', 'dry-prairie'],
    shortDesc: 'Before 1860, the Checkered White was the native white butterfly of eastern fields and gardens. Cabbage White arrived and spread from Quebec to California in forty years. The Checkered White retreated to coastal barrens and dry prairie remnants — where it still flies.',
  },
  {
    id: 'eastern-tailed-blue',
    name: 'Eastern Tailed-Blue',
    scientificName: 'Cupido comyntas',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/49773696/large.jpg',
    photoCredit: 'petrichor / CC BY-NC via iNaturalist',
    page: 'eastern-tailed-blue' as Page,
    status: 'common' as const,
    habitatTags: ['meadow', 'clover-field', 'open-land'],
    shortDesc: 'The smallest blue butterfly in the eastern United States — wingspan under one inch. The hindwing carries a tiny tail and two orange spots near the base, and the butterfly pivots these markings back and forth while resting, redirecting predator attacks away from its body.',
  },
  {
    id: 'gray-hairstreak',
    name: 'Gray Hairstreak',
    scientificName: 'Strymon melinus',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/261048551/large.jpg',
    photoCredit: 'Arlene Koziol / CC BY-NC via iNaturalist',
    page: 'gray-hairstreak' as Page,
    status: 'common' as const,
    habitatTags: ['meadow', 'garden', 'open-land'],
    shortDesc: 'The most widespread hairstreak in North America. Its caterpillar has been recorded feeding on over 200 plant species across more than 20 families — an unusually broad host range for a butterfly in this group. Adults pivot their hindwings while resting, rubbing the tails together to simulate antenna movement and redirect predator strikes.',
  },
  {
    id: 'sleepy-orange',
    name: 'Sleepy Orange',
    scientificName: 'Eurema nicippe',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/178930280/large.jpeg',
    photoCredit: 'Nick Carlson / CC BY-NC via iNaturalist',
    page: 'sleepy-orange' as Page,
    status: 'stable' as const,
    habitatTags: ['legume-garden', 'open-meadow'],
    shortDesc: 'The Sleepy Orange is named for a small black arc on its forewing that curves like a closed eye — not for its behavior. When disturbed from a legume plant, it launches into the fastest, most direction-changing flight in the patch. The butterfly re-colonizes the northern states each June from a permanent year-round population along the Gulf coastal plain.',
  },
  {
    id: 'little-yellow',
    name: 'Little Yellow',
    scientificName: 'Pyrisitia lisa',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/305807245/large.jpeg',
    photoCredit: 'cseantracy / CC BY-NC via iNaturalist',
    page: 'little-yellow' as Page,
    status: 'stable' as const,
    habitatTags: ['legume-garden', 'open-meadow'],
    shortDesc: 'The Little Yellow is the smallest sulphur in the eastern United States. Males are lemon yellow; females range from yellow to nearly white — naturalists named the white female form as a separate species before field observers watched paired adults and corrected the error. It uses Partridge Pea, Wild Senna, and related legumes as host plants, and re-colonizes the northern states each summer from the Gulf coastal plain.',
  },
  {
    id: 'zebra-swallowtail',
    name: 'Zebra Swallowtail',
    scientificName: 'Eurytides marcellus',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/145846511/large.jpeg',
    photoCredit: 'pteranodon / CC BY-NC via iNaturalist',
    page: 'zebra-swallowtail' as Page,
    status: 'stable' as const,
    habitatTags: ['woodland-edge', 'open-meadow'],
    shortDesc: 'The Zebra Swallowtail is the only swallowtail in eastern North America with hindwing tails nearly as long as the hindwing itself. Its caterpillar feeds exclusively on pawpaw leaves — no other plant is accepted. A female presses her front feet against a leaf to read its chemistry; if it is not pawpaw, she lifts off and keeps searching. Spring-form adults emerge in April with shorter tails; summer-form adults emerge in June with longer tails and more blue-green in the bands.',
  },
  {
    id: 'coral-hairstreak',
    name: 'Coral Hairstreak',
    scientificName: 'Satyrium titus',
    emoji: '🦋',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/210898298/large.jpg',
    photoCredit: 'bevlynn99 / CC BY-NC via iNaturalist',
    page: 'coral-hairstreak' as Page,
    status: 'stable' as const,
    habitatTags: ['woodland-edge', 'open-meadow'],
    shortDesc: 'The Coral Hairstreak is the only hairstreak in the eastern United States without tails at the hindwing rear corner. In their place, a row of coral-orange spots spans the full lower hindwing edge. It produces one brood per year, flying for six weeks in July. The female lays a single egg on wild plum or black cherry bark in August; that egg overwinters on the bark and hatches when the plum flowers open the following May.',
  },
  {
    id: 'leonards-skipper',
    name: "Leonard's Skipper",
    scientificName: 'Hesperia leonardus',
    emoji: '🦋',
    shortDesc: "One of the latest-flying skippers in the east — on the wing in late August and September when most other skippers have finished. Feeds almost exclusively on native little bluestem as a caterpillar. Populations have declined alongside the loss of native prairie and savanna grasslands where little bluestem once dominated.",
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Hesperia_leonardus.jpg',
    photoCredit: 'Patrick Coin / CC BY-SA 2.5',
    page: 'leonards-skipper',
    habitatTags: ['prairie', 'little-bluestem', 'open-land'],
  },
  {
    id: 'cobweb-skipper',
    name: 'Cobweb Skipper',
    scientificName: 'Hesperia metea',
    emoji: '🦋',
    shortDesc: 'Flies for only three to four weeks in spring — one of the earliest skippers, on the wing in late April and May before most others appear. Caterpillars feed exclusively on little bluestem and beard grass, building shelters by folding grass blades and tying them with silk.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Hesperia_metea_male_dorsal_Patrick_Coin.jpg',
    photoCredit: 'Patrick Coin / CC BY-SA 2.5',
    page: 'cobweb-skipper',
    habitatTags: ['prairie', 'little-bluestem', 'dry-open-land'],
  },
  {
    id: 'canada-goldenrod',
    name: 'Canada Goldenrod',
    scientificName: 'Solidago canadensis',
    emoji: '🌿',
    shortDesc: 'Hosts over 100 insect species as caterpillar food plants — more than almost any other herbaceous plant in eastern North America. The gall on its stem (a round swelling visible in winter) is produced by a fly larva that overwinters inside and is excavated and eaten by Downy Woodpeckers.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Solidago_canadensis_20050815_002.jpg',
    photoCredit: 'Kaldari / CC0',
    page: 'canada-goldenrod',
    habitatTags: ['meadow', 'edge', 'garden'],
  },
  {
    id: 'purple-coneflower',
    name: 'Purple Coneflower',
    scientificName: 'Echinacea purpurea',
    emoji: '🌸',
    shortDesc: "Produces seed heads that remain standing through winter and are visited by American Goldfinch and other finches that extract seeds directly from the head. The flower's central cone produces both pollen and nectar, supporting a wider range of bee species than most cultivated garden flowers.",
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Echinacea_purpurea.jpg/960px-Echinacea_purpurea.jpg',
    photoCredit: 'Meneerke bloem / CC BY-SA 3.0',
    page: 'purple-coneflower',
    habitatTags: ['meadow', 'garden', 'prairie'],
  },
  {
    id: 'joe-pye-weed',
    name: 'Joe-Pye Weed',
    scientificName: 'Eutrochium purpureum',
    emoji: '🌸',
    shortDesc: 'Reaches 6–8 feet tall and blooms in late July through September — one of the tallest and latest-blooming native composites in the eastern US. A single plant in full bloom can carry dozens of nectaring butterflies simultaneously.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Eupatorium_purpureum.jpg',
    photoCredit: 'Fritzflohrreynolds / CC BY-SA 3.0',
    page: 'joe-pye-weed',
    habitatTags: ['meadow', 'edge', 'wetland-edge'],
  },
  {
    id: 'common-milkweed',
    name: 'Common Milkweed',
    scientificName: 'Asclepias syriaca',
    emoji: '🌸',
    shortDesc: 'The only plant on which monarch butterflies lay their eggs. Eliminated from roughly 165 million acres of Midwest farmland since herbicide-resistant crops were introduced in 1996.',
    status: 'declining',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Milkweed_Flowers.JPG/960px-Milkweed_Flowers.JPG',
    photoCredit: 'William Warby / CC BY 2.0',
    page: 'common-milkweed',
    habitatTags: ['meadow', 'edge', 'roadsides'],
  },
  {
    id: 'swamp-milkweed',
    name: 'Swamp Milkweed',
    scientificName: 'Asclepias incarnata',
    emoji: '🌸',
    shortDesc: 'Tolerates wet soils where Common Milkweed cannot establish. Its narrower leaves and pink flowers support a different mix of specialist insects alongside monarchs — including several milkweed beetles and the milkweed tussock moth.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Asclepias_incarnata_-_Swamp_milkweed_-_geograph.org.uk_-_2030131.jpg/960px-Asclepias_incarnata_-_Swamp_milkweed_-_geograph.org.uk_-_2030131.jpg',
    photoCredit: 'Robert Nyman / CC BY-SA 2.0',
    page: 'swamp-milkweed',
    habitatTags: ['wetland-edge', 'rain-garden', 'meadow'],
  },
  {
    id: 'butterfly-weed',
    name: 'Butterfly Weed',
    scientificName: 'Asclepias tuberosa',
    emoji: '🌸',
    shortDesc: 'Blooms orange in a family where most species bloom pink or white. The root grows deep and is almost impossible to transplant — this milkweed must be established from seed or young nursery plants; it will not survive being moved once established.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Asclepias_tuberosa_-_Butterfly_Weed.jpg/960px-Asclepias_tuberosa_-_Butterfly_Weed.jpg',
    photoCredit: 'Bob Peterson / CC BY 2.0',
    page: 'butterfly-weed',
    habitatTags: ['dry-meadow', 'garden', 'prairie'],
  },
  {
    id: 'new-england-aster',
    name: 'New England Aster',
    scientificName: 'Symphyotrichum novae-angliae',
    emoji: '🌸',
    shortDesc: 'Blooms in September and October — among the last native flowers of the season. The late bloom provides nectar for migrating monarchs and other butterflies building fat reserves for winter.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/New_England_aster_%28Symphyotrichum_novae-angliae%29.jpg/960px-New_England_aster_%28Symphyotrichum_novae-angliae%29.jpg',
    photoCredit: 'Joshua Mayer / CC BY-SA 2.0',
    page: 'new-england-aster',
    habitatTags: ['meadow', 'garden', 'edge'],
  },
  {
    id: 'wild-bergamot',
    name: 'Wild Bergamot',
    scientificName: 'Monarda fistulosa',
    emoji: '🌸',
    shortDesc: 'Blooms in July and August and is one of the premier native nectar plants for bumble bees. The ragged, tubular flowers require a bee to push into the flower to reach nectar — a shape that favors long-tongued bees over short-tongued ones.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Monarda_fistulosa.jpg/500px-Monarda_fistulosa.jpg',
    photoCredit: 'Superior National Forest / CC BY 2.0',
    page: 'wild-bergamot',
    habitatTags: ['meadow', 'garden', 'prairie'],
  },
  {
    id: 'new-jersey-tea',
    name: 'New Jersey Tea',
    scientificName: 'Ceanothus americanus',
    emoji: '🌿',
    shortDesc: 'A small native shrub that fixes nitrogen through root bacteria — it improves the soil it grows in. Hosts the Spring Azure butterfly as a larval food plant; caterpillars feed on flower buds and developing seeds.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Ceanothus_americanus.jpg',
    photoCredit: 'Rob Routledge / CC BY-SA 3.0',
    page: 'new-jersey-tea',
    habitatTags: ['dry-prairie', 'edge', 'woodland-edge'],
  },
  {
    id: 'wild-columbine',
    name: 'Wild Columbine',
    scientificName: 'Aquilegia canadensis',
    emoji: '🌸',
    shortDesc: 'The nodding red-and-yellow flowers match the tongue length of Ruby-throated Hummingbirds almost exactly — the flower tube is shaped to deposit pollen on the hummingbird\'s forehead as it hovers to drink nectar.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Aquilegia_canadensis_flowers.jpg',
    photoCredit: 'Crusier / CC BY-SA 3.0',
    page: 'wild-columbine',
    habitatTags: ['woodland-edge', 'garden', 'rocky-slope'],
  },
  {
    id: 'black-eyed-susan',
    name: 'Black-Eyed Susan',
    scientificName: 'Rudbeckia hirta',
    emoji: '🌸',
    shortDesc: 'One of the most host-plant-dense native flowers for insects. Hosts 17 bee species, 12 caterpillar species, and is one of the top four plants for supporting native bee diversity in eastern North American research plots.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Rudbeckia_hirta_-_Black-eyed_Susan_-_geograph.org.uk_-_2003764.jpg/960px-Rudbeckia_hirta_-_Black-eyed_Susan_-_geograph.org.uk_-_2003764.jpg',
    photoCredit: 'Philip Halling / CC BY-SA 2.0',
    page: 'black-eyed-susan',
    habitatTags: ['meadow', 'garden', 'prairie'],
  },
  {
    id: 'virginia-bluebell',
    name: 'Virginia Bluebell',
    scientificName: 'Mertensia virginica',
    emoji: '🌸',
    shortDesc: 'One of the earliest spring ephemerals — the entire above-ground plant emerges, blooms, sets seed, and dies back underground between March and June. Blooms before most trees fully leaf out, capturing the brief window of high light on the forest floor.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Virginia-Bluebells.jpg/960px-Virginia-Bluebells.jpg',
    photoCredit: 'Famartin / CC BY-SA 4.0',
    page: 'virginia-bluebell',
    habitatTags: ['floodplain', 'woodland', 'spring-ephemeral'],
  },
  {
    id: 'buttonbush',
    name: 'Buttonbush',
    scientificName: 'Cephalanthus occidentalis',
    emoji: '🌿',
    shortDesc: 'One of the few shrubs that flowers in standing water. The spherical white flowers bloom in July and August and are among the most visited native flowers by long-tongued bees and butterflies in wetland edge habitats.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Cephalanthus_occidentalis.jpg/960px-Cephalanthus_occidentalis.jpg',
    photoCredit: 'Famartin / CC BY-SA 4.0',
    page: 'buttonbush',
    habitatTags: ['wetland', 'rain-garden', 'water-edge'],
  },
  {
    id: 'ironweed',
    name: 'Tall Ironweed',
    scientificName: 'Vernonia gigantea',
    emoji: '🌸',
    shortDesc: 'Blooms in August — the same peak butterfly migration window — with vivid purple flower heads that attract nectaring monarchs, swallowtails, and bumble bees simultaneously. The flower color is produced by cyanidin pigments not found in most plants.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Vernonia_gigantea.jpg/960px-Vernonia_gigantea.jpg',
    photoCredit: 'Fritzflohrreynolds / CC BY-SA 3.0',
    page: 'ironweed',
    habitatTags: ['meadow', 'edge', 'garden'],
  },
  {
    id: 'golden-alexanders',
    name: 'Golden Alexanders',
    scientificName: 'Zizia aurea',
    emoji: '🌸',
    shortDesc: 'One of the earliest-blooming native wildflowers — in flower by late April. Hosts Black Swallowtail caterpillars as one of their primary spring food plants, alongside wild parsnip and cow parsley in the carrot family.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Golden_Alexanders.jpg',
    photoCredit: 'Fritzflohrreynolds / CC BY-SA 3.0',
    page: 'golden-alexanders',
    habitatTags: ['meadow', 'garden', 'edge'],
  },
  {
    id: 'partridge-pea',
    name: 'Partridge Pea',
    scientificName: 'Chamaecrista fasciculata',
    emoji: '🌿',
    shortDesc: 'The primary larval host for the Cloudless Sulphur, Little Yellow, and Sleepy Orange — three sulphur butterflies whose caterpillars develop on this plant. A summer annual that self-seeds readily from year to year.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Chamaecrista_fasciculata_2.jpg/960px-Chamaecrista_fasciculata_2.jpg',
    photoCredit: 'Fritzflohrreynolds / CC BY-SA 3.0',
    page: 'partridge-pea',
    habitatTags: ['dry-meadow', 'open-ground', 'legume-garden'],
  },
  {
    id: 'wild-senna',
    name: 'Wild Senna',
    scientificName: 'Senna hebecarpa',
    emoji: '🌿',
    shortDesc: 'A tall perennial legume — reaching 5–6 feet — that hosts Cloudless Sulphur, Sleepy Orange, and Little Yellow caterpillars. Produces extrafloral nectaries on the leaf stems that attract ants, creating a multi-species dynamic around a single plant.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/200395538/large.jpg',
    photoCredit: 'Eddie Dunbar / CC BY-NC via iNaturalist',
    page: 'wild-senna',
    habitatTags: ['legume-garden', 'woodland-edge', 'meadow'],
  },
  {
    id: 'wild-blue-indigo',
    name: 'Wild Blue Indigo',
    scientificName: 'Baptisia australis',
    emoji: '🌿',
    shortDesc: 'A native legume that blooms in May with blue-violet flower spikes before most native wildflowers open. The Wild Indigo Duskywing lays its eggs on Baptisia leaves and on no other plant — its population in any county tracks how much Wild Blue Indigo remains. The taproot reaches several feet deep and the same crown returns each spring for decades.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/8193465/large.jpg',
    photoCredit: 'aarongunnar / CC BY via iNaturalist',
    page: 'wild-blue-indigo' as Page,
    habitatTags: ['legume-garden', 'open-meadow', 'woodland-edge'],
  },
  {
    id: 'maryland-senna',
    name: 'Maryland Senna',
    scientificName: 'Senna marilandica',
    emoji: '🌿',
    shortDesc: 'A native perennial legume that blooms in July with yellow flower clusters. Cloudless Sulphur caterpillars are green when eating the leaves and yellow when eating the flowers — the same caterpillar, on the same stem, depending on what it is currently digesting. Maryland Senna extends into the Southeast where Wild Senna does not reach, hosting the same three sulphur species.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/24375937/large.jpg',
    photoCredit: 'sandywolkenberg / CC BY via iNaturalist',
    page: 'maryland-senna' as Page,
    habitatTags: ['legume-garden', 'open-meadow', 'woodland-edge'],
  },
  {
    id: 'wild-indigo-duskywing',
    name: 'Wild Indigo Duskywing',
    scientificName: 'Erynnis baptisiae',
    emoji: '🦋',
    shortDesc: 'A dark brown skipper butterfly on the wing from late April through July. The female finds Baptisia leaves by tasting the surface with chemoreceptors in her feet — she lays one egg per leaflet across several plants rather than concentrating on one. When Wild Blue Indigo disappears from a county, the Wild Indigo Duskywing disappears with it.',
    status: 'uncommon',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/227093239/large.jpg',
    photoCredit: 'tezster / CC BY-NC via iNaturalist',
    page: 'wild-indigo-duskywing' as Page,
    habitatTags: ['open-meadow', 'garden', 'woodland-edge'],
  },
  {
    id: 'frosted-elfin',
    name: 'Frosted Elfin',
    scientificName: 'Callophrys irus',
    emoji: '🦋',
    shortDesc: 'A thumbnail-sized hairstreak butterfly that lays its eggs inside Baptisia flower buds — the caterpillar feeds on the flowers and developing seed pods, not leaves. Adults fly for three weeks in late April and May, then disappear underground for eleven months. NatureServe rates the species globally imperiled, and more than 25 states list it as endangered.',
    status: 'endangered',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/11499071/large.jpg',
    photoCredit: 'tpalmer / CC BY-NC via iNaturalist',
    page: 'frosted-elfin' as Page,
    habitatTags: ['open-meadow', 'garden', 'dry-barrens'],
  },
  {
    id: 'wild-lupine',
    name: 'Wild Lupine',
    scientificName: 'Lupinus perennis',
    emoji: '🌿',
    shortDesc: 'A native perennial legume of sandy, acidic soils that blooms in May with blue-violet flower spikes. Wild Lupine is the only larval host plant for the federally endangered Karner Blue and the primary northeastern host for Frosted Elfin — when Lupine disappears from a site, both butterflies disappear with it.',
    status: 'declining',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/18285247/large.jpg',
    photoCredit: 'bouteloua / CC BY-NC via iNaturalist',
    page: 'wild-lupine' as Page,
    habitatTags: ['dry-barrens', 'open-meadow', 'legume-garden'],
  },
  {
    id: 'karner-blue',
    name: 'Karner Blue',
    scientificName: 'Plebejus samuelis',
    emoji: '🦋',
    shortDesc: 'A thumbnail-sized butterfly, cerulean blue in males, that flies only in May–June and July–August along Wild Lupine stands. Federally endangered since 1992. The egg overwinters at the lupine root crown from August through April — when the plant is cleared in autumn, the next generation hatches onto bare ground.',
    status: 'endangered',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/205496077/large.jpg',
    photoCredit: 'sarahjomin / CC BY-NC via iNaturalist',
    page: 'karner-blue' as Page,
    habitatTags: ['dry-barrens', 'open-meadow', 'pine-barren'],
  },
  {
    id: 'prairie-dropseed',
    name: 'Prairie Dropseed',
    scientificName: 'Sporobolus heterolepis',
    emoji: '🌿',
    shortDesc: 'A fine-textured native grass that forms tight mounds and blooms with small coriander-scented flowers in late summer. One of the few native grasses with ornamental appeal in all four seasons — green in spring, flowering in August, copper-orange in fall, and straw-colored through winter.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Prairie_Dropseed_%28Sporobolus_heterolepis%29_%2822017597574%29.jpg',
    photoCredit: 'Joshua Mayer / CC BY-SA 2.0',
    page: 'prairie-dropseed',
    habitatTags: ['dry-prairie', 'garden', 'edge'],
  },
  {
    id: 'little-bluestem',
    name: 'Little Bluestem',
    scientificName: 'Schizachyrium scoparium',
    emoji: '🌿',
    shortDesc: "One of the most widespread native grasses in eastern North America — present across the continent's prairie biome. Hosts Leonard's Skipper and Cobweb Skipper caterpillars. Turns deep copper-red in fall and holds its seed heads through winter, providing cover and food for sparrows and juncos.",
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Little_bluestem_Schizachyrium_scoparium_closeup.jpg/960px-Little_bluestem_Schizachyrium_scoparium_closeup.jpg',
    photoCredit: 'Fritzflohrreynolds / CC BY-SA 3.0',
    page: 'little-bluestem',
    habitatTags: ['dry-prairie', 'garden', 'edge'],
  },
  {
    id: 'white-oak',
    name: 'White Oak',
    scientificName: 'Quercus alba',
    emoji: '🌳',
    shortDesc: 'Hosts more caterpillar species than any other tree genus in North America — over 500 species of Lepidoptera use oaks as larval food plants. A single white oak in full leaf can support the equivalent of hundreds of pounds of insect biomass in a season.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Quercus_alba.jpg',
    photoCredit: 'James St. John / CC BY 2.0',
    page: 'white-oak',
    habitatTags: ['woodland', 'canopy', 'garden'],
  },
  {
    id: 'black-cherry',
    name: 'Black Cherry',
    scientificName: 'Prunus serotina',
    emoji: '🌳',
    shortDesc: 'Hosts more caterpillar species than almost any deciduous tree except oak — over 450 species in the east. The spring emergence of caterpillars on black cherry is timed with the peak demand for protein-rich insect food by nesting songbirds.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Prunus_serotina_in_flower.jpg',
    photoCredit: 'Famartin / CC BY-SA 3.0',
    page: 'black-cherry',
    habitatTags: ['woodland', 'edge', 'canopy'],
  },
  {
    id: 'serviceberry',
    name: 'Serviceberry',
    scientificName: 'Amelanchier arborea',
    emoji: '🌳',
    shortDesc: 'One of the earliest trees to bloom in spring — flowers open before the leaves fully emerge, making it visible from a distance when everything else is still bare. Produces fruit in June, timed to the migration of many songbird species.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Amelanchier_arborea_flowers.jpg/960px-Amelanchier_arborea_flowers.jpg',
    photoCredit: 'Famartin / CC BY-SA 4.0',
    page: 'serviceberry',
    habitatTags: ['woodland-edge', 'garden', 'understory'],
  },
  {
    id: 'pawpaw',
    name: 'Pawpaw',
    scientificName: 'Asimina triloba',
    emoji: '🌳',
    shortDesc: 'The only host plant for the Zebra Swallowtail — a female presses her feet against the leaf surface to detect acetogenins, the same compounds that make pawpaw leaves resistant to most insect feeding. The largest edible fruit native to North America, and one of the few native understory trees that deer consistently leave untouched.',
    status: 'common',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/592543131/large.jpg',
    photoCredit: 'roadside_rambler / CC BY-NC via iNaturalist',
    page: 'pawpaw' as Page,
    habitatTags: ['understory', 'woodland-edge', 'garden'],
  },
  {
    id: 'spicebush',
    name: 'Northern Spicebush',
    scientificName: 'Lindera benzoin',
    emoji: '🌿',
    shortDesc: 'The primary larval host for the Spicebush Swallowtail. The small yellow flowers bloom before the leaves emerge in March, providing early nectar for native bees. Dioecious — male and female flowers on separate plants — so a berry-producing plant requires a pollinating neighbor.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Lindera_benzoin.jpg',
    photoCredit: 'Nicholas A. Tonelli / CC BY 2.0',
    page: 'spicebush',
    habitatTags: ['understory', 'woodland-edge', 'moist-soil'],
  },
  {
    id: 'elderberry',
    name: 'American Elderberry',
    scientificName: 'Sambucus canadensis',
    emoji: '🌿',
    shortDesc: 'Produces flat-topped clusters of white flowers in June and purple-black berries in August. The berries are consumed by over 120 bird species during fall migration. Hollow elderberry stems are used as nesting tunnels by several cavity-nesting native bee species.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Sambucus_nigra_-_American_Elderberry_-_Elderflower.jpg/960px-Sambucus_nigra_-_American_Elderberry_-_Elderflower.jpg',
    photoCredit: 'Famartin / CC BY-SA 4.0',
    page: 'elderberry',
    habitatTags: ['edge', 'meadow', 'wetland-edge'],
  },
  {
    id: 'virginia-creeper',
    name: 'Virginia Creeper',
    scientificName: 'Parthenocissus quinquefolia',
    emoji: '🌿',
    shortDesc: 'Produces berries in September that are among the most energy-dense available to migrating songbirds — high in fat content relative to most native fruits. Berries are poisonous to humans but consumed readily by over 35 bird species.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Parthenocissus_quinquefolia_10.jpg/960px-Parthenocissus_quinquefolia_10.jpg',
    photoCredit: 'Famartin / CC BY-SA 4.0',
    page: 'virginia-creeper',
    habitatTags: ['woodland-edge', 'garden', 'wall'],
  },
  {
    id: 'winterberry-holly',
    name: 'Winterberry Holly',
    scientificName: 'Ilex verticillata',
    emoji: '🌿',
    shortDesc: 'Drops its leaves in fall to reveal densely clustered red berries that persist on bare branches through winter. The berries are consumed by American Robins, Cedar Waxwings, and other frugivores when other food sources are exhausted.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ilex_verticillata.jpg/960px-Ilex_verticillata.jpg',
    photoCredit: 'Carl Wycoff / CC BY 2.0',
    page: 'winterberry-holly',
    habitatTags: ['wetland-edge', 'garden', 'shrub'],
  },
  {
    id: 'arrowwood-viburnum',
    name: 'Arrowwood Viburnum',
    scientificName: 'Viburnum dentatum',
    emoji: '🌿',
    shortDesc: 'Produces white flower clusters in May and blue-black berries in September. Documented as a host plant for over 100 species of Lepidoptera caterpillars, and the fall berries are consumed by migratory thrushes, waxwings, and sparrows.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Viburnum_dentatum2.jpg',
    photoCredit: 'Fritzflohrreynolds / CC BY-SA 3.0',
    page: 'arrowwood-viburnum',
    habitatTags: ['woodland-edge', 'shrub', 'garden'],
  },
  {
    id: 'virginia-bluebell-plant',
    name: 'Virginia Bluebell (Plant Profile)',
    scientificName: 'Mertensia virginica',
    emoji: '🌸',
    shortDesc: 'Only present in full leaf for 10–12 weeks in spring, then dormant underground for the rest of the year. Must be marked at leaf-out to avoid accidental disturbance while dormant.',
    status: 'common',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Virginia-Bluebells.jpg/960px-Virginia-Bluebells.jpg',
    photoCredit: 'Famartin / CC BY-SA 4.0',
    page: null,
    habitatTags: ['floodplain', 'woodland', 'spring-ephemeral'],
  },
  {
    id: 'juvenals-duskywing',
    name: "Juvenal's Duskywing",
    scientificName: 'Erynnis juvenalis',
    emoji: '🦋',
    shortDesc: "A dark brown skipper on the wing in a single brood from late April through June — gone by midsummer. The caterpillar rolls a white oak leaf into a silk tube and feeds inside it through summer, then overwinters as a larva in fallen rolled leaves on the forest floor. Raking those leaves in autumn removes the overwintering cohort before it can pupate in spring.",
    status: 'declining',
    photo: 'https://inaturalist-open-data.s3.amazonaws.com/photos/17117409/large.jpg',
    photoCredit: 'mellis / CC BY via iNaturalist',
    page: 'juvenals-duskywing' as Page,
    habitatTags: ['woodland', 'woodland-edge', 'leaf-litter'],
  },
]

interface SpeciesGalleryProps {
  onNavigate: (page: Page) => void
}

const HABITAT_TAGS = [
  { id: 'all', label: 'All Habitats' },
  { id: 'meadow', label: 'Meadow & Prairie' },
  { id: 'woodland', label: 'Woodland' },
  { id: 'woodland-edge', label: 'Woodland Edge' },
  { id: 'wetland', label: 'Wetland' },
  { id: 'garden', label: 'Garden' },
  { id: 'edge', label: 'Edge Habitat' },
  { id: 'leaf-litter', label: 'Leaf Litter' },
  { id: 'open-land', label: 'Open Land' },
]

const STATUS_LABELS: Record<Status, string> = {
  common: 'Common',
  declining: 'Declining',
  endangered: 'Endangered',
}

const STATUS_COLORS: Record<Status, string> = {
  common: '#2e7d32',
  declining: '#f57c00',
  endangered: '#c62828',
}

export default function SpeciesGallery({ onNavigate }: SpeciesGalleryProps) {
  return (
    <div className="page">
      <section className="hero" style={{ paddingBottom: '1rem' }}>
        <div className="hero__eyebrow">All Species</div>
        <h1>The Species Gallery</h1>
        <p className="hero__lead">
          Every species on this site — butterflies, birds, frogs, mammals, and plants — with a
          short description of what makes each one worth noticing. Click any card to read the
          full profile.
        </p>
      </section>

      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '1.5rem', marginTop: '2rem' }}>
        {SPECIES.filter(s => s.page !== null).map((species) => (
          <div
            key={species.id}
            className="species-card"
            onClick={() => species.page && onNavigate(species.page)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if ((e.key === 'Enter' || e.key === ' ') && species.page) {
                onNavigate(species.page)
              }
            }}
            style={{ cursor: 'pointer' }}
          >
            <div className="species-card__image-wrap">
              <img
                src={species.photo}
                alt={species.name}
                className="species-card__image"
                loading="lazy"
                onError={(e) => {
                  e.currentTarget.src = PHOTO_FALLBACK
                }}
              />
            </div>
            <div className="species-card__body">
              <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.5rem', flexWrap: 'wrap' }}>
                <h3 className="species-card__name">{species.emoji} {species.name}</h3>
                <span
                  className="species-card__status"
                  style={{ color: STATUS_COLORS[species.status] }}
                >
                  {STATUS_LABELS[species.status]}
                </span>
              </div>
              <p className="species-card__sci-name">{species.scientificName}</p>
              <p className="species-card__desc">{species.shortDesc}</p>
              <div className="species-card__tags">
                {species.habitatTags.map(tag => (
                  <span key={tag} className="species-card__tag">{tag}</span>
                ))}
              </div>
            </div>
          </div>
        ))}
      </div>

      <section style={{ marginTop: '3rem' }} aria-labelledby="photo-credits-heading">
        <h2 id="photo-credits-heading">Photo Credits</h2>
        <p>
          All photographs are sourced from Wikimedia Commons or iNaturalist under Creative Commons
          licenses (CC BY 2.0, CC BY-SA 3.0, CC BY-SA 4.0, or CC BY-NC 4.0). No modifications were made.
        </p>
      </section>
    </div>
  )
}