import type { Page } from '../App'

type Status = 'Common' | 'Declining' | 'Endangered'

type SpeciesItem = {
  name: string
  scientificName: string
  emoji: string
  summary: string
  status: Status
  page: Page
  habitats: string[]
}

const SPECIES: SpeciesItem[] = [
  // ── INDICATOR SPECIES ─────────────────────────────────────────────────────
  { name: 'Monarch Butterfly', scientificName: 'Danaus plexippus', emoji: '\ud83e\udd8b', summary: 'Depends on milkweed to reproduce and remains one of Camp Monarch\'s clearest indicator species.', status: 'Endangered', page: 'why-monarchs', habitats: ['milkweed', 'open meadow', 'garden'] },
  { name: 'Firefly', scientificName: 'Photinus pyralis', emoji: '\u2728', summary: 'Needs leaf litter and dark summer nights to complete its life cycle.', status: 'Declining', page: 'fireflies', habitats: ['leaf litter', 'tall grass', 'edge'] },
  { name: 'Eastern Box Turtle', scientificName: 'Terrapene carolina', emoji: '\ud83d\udc22', summary: 'Uses small home ranges and suffers when roads cut through familiar territory.', status: 'Declining', page: 'box-turtles', habitats: ['woodland', 'edge', 'leaf litter'] },
  { name: 'Native Bees', scientificName: '4,000+ species', emoji: '\ud83d\udc1d', summary: 'Most species are solitary nesters that need flowers and exposed or lightly covered soil.', status: 'Declining', page: 'native-bees', habitats: ['meadow', 'garden', 'bare soil'] },
  { name: 'American Bumble Bee', scientificName: 'Bombus pensylvanicus', emoji: '\ud83d\udc1d', summary: 'A once-common prairie pollinator now missing from much of its former range.', status: 'Endangered', page: 'american-bumble-bee', habitats: ['meadow', 'garden', 'open land'] },

  // ── AMPHIBIANS ────────────────────────────────────────────────────────────
  { name: 'Northern Spring Peeper', scientificName: 'Pseudacris crucifer', emoji: '\ud83d\udc38', summary: 'A tiny frog whose early spring calls signal healthy seasonal wetlands.', status: 'Common', page: 'spring-peeper', habitats: ['wetland', 'vernal pool', 'woodland edge'] },
  { name: 'Eastern Gray Treefrog', scientificName: 'Hyla versicolor', emoji: '\ud83d\udc38', summary: 'A camouflage specialist that uses trees, shrubs, and nearby water.', status: 'Common', page: 'gray-tree-frogs', habitats: ['woodland edge', 'garden', 'wetland edge'] },
  { name: 'Wood Frog', scientificName: 'Lithobates sylvaticus', emoji: '\ud83d\udc38', summary: 'Can freeze through winter and recover when spring returns.', status: 'Common', page: 'wood-frog', habitats: ['woodland', 'leaf litter', 'vernal pool'] },
  { name: 'American Toad', scientificName: 'Anaxyrus americanus', emoji: '\ud83d\udc38', summary: 'A backyard insect hunter that benefits from loose soil and pesticide-free ground cover.', status: 'Common', page: 'toad', habitats: ['garden', 'woodland edge', 'open ground'] },

  // ── REPTILES ──────────────────────────────────────────────────────────────
  { name: 'Eastern Garter Snake', scientificName: 'Thamnophis sirtalis', emoji: '\ud83d\udc0d', summary: 'A cold-tolerant snake that depends on layered ground habitat and prey-rich yards.', status: 'Common', page: 'garter-snake', habitats: ['garden', 'meadow', 'woodland edge'] },

  // ── MAMMALS ───────────────────────────────────────────────────────────────
  { name: 'Eastern Chipmunk', scientificName: 'Tamias striatus', emoji: '\ud83d\udc3f', summary: 'Buries and forgets seeds, helping regenerate native woodland edges.', status: 'Common', page: 'eastern-chipmunk', habitats: ['woodland edge', 'garden', 'edge'] },
  { name: 'Eastern Gray Squirrel', scientificName: 'Sciurus carolinensis', emoji: '\ud83d\udc3f', summary: 'Moves acorns across suburban landscapes and unintentionally plants future trees.', status: 'Common', page: 'eastern-gray-squirrel', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Eastern Cottontail', scientificName: 'Sylvilagus floridanus', emoji: '\ud83d\udc07', summary: 'Raises young in shallow nests hidden in unmowed grass and low cover.', status: 'Common', page: 'eastern-cottontail', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Virginia Opossum', scientificName: 'Didelphis virginiana', emoji: '\ud83e\udd94', summary: 'North America\'s only marsupial and a frequent nighttime insect and carrion scavenger.', status: 'Common', page: 'virginia-opossum', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Striped Skunk', scientificName: 'Mephitis mephitis', emoji: '\ud83e\udda8', summary: 'Excavates lawn grubs and thrives where yards retain den cover and insect life.', status: 'Common', page: 'striped-skunk', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Red Fox', scientificName: 'Vulpes vulpes', emoji: '\ud83e\udd8a', summary: 'A mobile predator that uses connected green space and abundant small mammals.', status: 'Common', page: 'red-fox', habitats: ['woodland edge', 'suburban', 'garden'] },
  { name: 'Little Brown Bat', scientificName: 'Myotis lucifugus', emoji: '\ud83e\udd87', summary: 'Consumes large numbers of insects but has been devastated by white-nose syndrome.', status: 'Declining', page: 'little-brown-bat', habitats: ['woodland edge', 'wetland edge', 'suburban'] },

  // ── BIRDS ─────────────────────────────────────────────────────────────────
  { name: 'Downy Woodpecker', scientificName: 'Dryobates pubescens', emoji: '\ud83d\udc26', summary: 'Uses small trunks and stems that larger woodpeckers often ignore.', status: 'Common', page: 'downy-woodpecker', habitats: ['woodland', 'edge', 'garden'] },
  { name: 'Northern Flicker', scientificName: 'Colaptes auratus', emoji: '\ud83d\udc26', summary: 'A ground-feeding woodpecker that follows ant-rich open habitat.', status: 'Declining', page: 'northern-flicker', habitats: ['open woodland', 'edge', 'lawn'] },
  { name: 'Eastern Bluebird', scientificName: 'Sialia sialis', emoji: '\ud83d\udc26', summary: 'Needs open feeding space, cavity nesting sites, and room to hunt insects low to the ground.', status: 'Declining', page: 'eastern-bluebird', habitats: ['open woodland', 'lawn', 'edge'] },
  { name: 'Black-Capped Chickadee', scientificName: 'Poecile atricapillus', emoji: '\ud83d\udc26', summary: 'Raises broods on caterpillars that come from native trees and shrubs.', status: 'Common', page: 'black-capped-chickadee', habitats: ['woodland', 'woodland edge', 'garden'] },
  { name: 'Northern Cardinal', scientificName: 'Cardinalis cardinalis', emoji: '\ud83d\udc26', summary: 'A familiar yard bird whose nestlings still rely heavily on insects.', status: 'Common', page: 'northern-cardinal', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'American Robin', scientificName: 'Turdus migratorius', emoji: '\ud83d\udc26', summary: 'Uses lawns, gardens, and edges where earthworms and insects remain abundant.', status: 'Common', page: 'american-robin', habitats: ['lawn', 'garden', 'woodland edge'] },
  { name: 'American Kestrel', scientificName: 'Falco sparverius', emoji: '\ud83d\udc26', summary: 'A small falcon declining with the loss of open grassland, cavity sites, and large insects.', status: 'Declining', page: 'american-kestrel', habitats: ['open woodland', 'edge', 'lawn'] },
  { name: 'Eastern Screech-Owl', scientificName: 'Megascops asio', emoji: '\ud83e\udd89', summary: 'A compact owl that often shares neighborhoods with people unnoticed.', status: 'Common', page: 'eastern-screech-owl', habitats: ['woodland', 'woodland edge', 'suburban'] },
  { name: 'Chimney Swift', scientificName: 'Chaetura pelagica', emoji: '\ud83d\udc26', summary: 'An aerial insectivore that now depends on surviving chimneys and healthy insect populations.', status: 'Declining', page: 'chimney-swift', habitats: ['open woodland', 'edge', 'suburban'] },
  { name: 'Eastern Towhee', scientificName: 'Pipilo erythrophthalmus', emoji: '\ud83d\udc26', summary: 'Needs dense understory and leaf litter for its scratch-foraging lifestyle.', status: 'Declining', page: 'eastern-towhee', habitats: ['woodland edge', 'edge', 'leaf litter'] },
  { name: 'Wood Thrush', scientificName: 'Hylocichla mustelina', emoji: '\ud83d\udc26', summary: 'A forest songbird in long decline because fragmentation reduces caterpillars and nesting success.', status: 'Declining', page: 'wood-thrush', habitats: ['woodland', 'woodland edge', 'leaf litter'] },
  { name: 'Eastern Meadowlark', scientificName: 'Sturnella magna', emoji: '\ud83d\udc26', summary: 'A grassland bird whose breeding success depends on large, uninterrupted meadow blocks.', status: 'Declining', page: 'eastern-meadowlark', habitats: ['meadow', 'open land', 'edge'] },
  { name: 'Baltimore Oriole', scientificName: 'Icterus galbula', emoji: '\ud83d\udc26', summary: 'Builds pendant nests in tall trees and has declined as elms and other suitable canopy structure disappeared.', status: 'Declining', page: 'baltimore-oriole', habitats: ['woodland edge', 'garden'] },
  { name: 'Scarlet Tanager', scientificName: 'Piranga olivacea', emoji: '\ud83d\udc26', summary: 'A forest-interior migrant that needs large blocks of canopy and suffers under heavy cowbird pressure.', status: 'Declining', page: 'scarlet-tanager', habitats: ['woodland'] },
  { name: 'Common Nighthawk', scientificName: 'Chordeiles minor', emoji: '\ud83d\udc26', summary: 'An aerial insectivore down 61% since 1966 — needs flying insects, dark summer skies, and flat gravel rooftops for nesting.', status: 'Declining', page: 'common-nighthawk', habitats: ['open sky', 'suburban', 'roof'] },
  { name: 'Purple Martin', scientificName: 'Progne subis', emoji: '\ud83d\udc26', summary: 'North America\'s largest swallow now nests almost exclusively in human-provided gourds and apartment boxes east of the Rockies.', status: 'Declining', page: 'purple-martin', habitats: ['open sky', 'suburban', 'water edge'] },
  { name: 'Red-Tailed Hawk', scientificName: 'Buteo jamaicensis', emoji: '\ud83d\udc26', summary: 'The most commonly seen hawk in North America — perches on fence posts and power lines scanning open ground for voles and mice.', status: 'Common', page: 'red-tailed-hawk', habitats: ['open woodland', 'edge', 'suburban'] },
  { name: 'Brown Thrasher', scientificName: 'Toxostoma rufum', emoji: '\ud83d\udc26', summary: 'Scratches through leaf litter with a long curved bill and produces the largest song repertoire of any North American bird.', status: 'Declining', page: 'brown-thrasher', habitats: ['woodland edge', 'thicket', 'leaf litter'] },
  { name: 'Carolina Wren', scientificName: 'Thryothorus ludovicianus', emoji: '\ud83d\udc26', summary: 'Hunts insects year-round in dense brush and will nest in almost any covered cavity — one of the loudest birds for its size.', status: 'Common', page: 'carolina-wren', habitats: ['woodland edge', 'thicket', 'garden'] },
  { name: 'Gray Catbird', scientificName: 'Dumetella carolinensis', emoji: '\ud83d\udc26', summary: 'Mimics other birds from dense thicket cover — its caterpillar-fed chicks depend on the insect community that native shrubs support.', status: 'Common', page: 'gray-catbird', habitats: ['woodland edge', 'thicket', 'garden'] },
  { name: 'Northern Mockingbird', scientificName: 'Mimus polyglottos', emoji: '\ud83d\udc26', summary: 'Can learn and repeat hundreds of song types — often sings through moonlit nights, defending year-round fruit and insect territories.', status: 'Common', page: 'northern-mockingbird', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Mourning Dove', scientificName: 'Zenaida macroura', emoji: '\ud83d\udc26', summary: 'One of the most abundant birds in North America — nests on thin horizontal branches and forages seeds from open ground.', status: 'Common', page: 'mourning-dove', habitats: ['open woodland', 'garden', 'edge'] },
  { name: 'Song Sparrow', scientificName: 'Melospiza melodia', emoji: '\ud83d\udc26', summary: 'A highly variable sparrow whose singing territory requires dense low vegetation and insect-rich ground.', status: 'Common', page: 'song-sparrow', habitats: ['woodland edge', 'wetland edge', 'garden'] },
  { name: 'Yellow-Rumped Warbler', scientificName: 'Setophaga coronata', emoji: '\ud83d\udc26', summary: 'One of the few warblers that can digest waxy berries — overwinters further north than nearly any other warbler because of it.', status: 'Common', page: 'yellow-rumped-warbler', habitats: ['woodland', 'woodland edge', 'garden'] },
  { name: 'Wild Turkey', scientificName: 'Meleagris gallopavo', emoji: '\ud83d\udc26', summary: 'A forest-floor omnivore that forages acorns and insects — one of the great conservation recovery stories of the 20th century.', status: 'Common', page: 'wild-turkey', habitats: ['woodland', 'open woodland', 'edge'] },
  { name: 'Eastern Phoebe', scientificName: 'Sayornis phoebe', emoji: '\ud83d\udc26', summary: 'Returns earlier than almost any other flycatcher — bobs its tail constantly and nests on bridges, buildings, and rock ledges.', status: 'Common', page: 'eastern-phoebe', habitats: ['woodland edge', 'stream edge', 'suburban'] },
  { name: 'Yellow Warbler', scientificName: 'Setophaga petechia', emoji: '\ud83d\udc26', summary: 'Nests in dense willow thickets near water — one of the most heavily cowbird-parasitized warblers in North America.', status: 'Declining', page: 'yellow-warbler', habitats: ['wetland edge', 'shrub', 'stream edge'] },
  { name: 'Ruby-Crowned Kinglet', scientificName: 'Corthylio calendula', emoji: '\ud83d\udc26', summary: 'A tiny insectivore that doubles its own weight before fall migration — forages in constant motion at all canopy levels.', status: 'Common', page: 'ruby-crowned-kinglet', habitats: ['woodland', 'woodland edge', 'garden'] },
  { name: 'Cedar Waxwing', scientificName: 'Bombycilla cedrorum', emoji: '\ud83d\udc26', summary: 'A social fruit-eater with waxy red wingtips — depends on native berry-producing shrubs and trees through every season.', status: 'Common', page: 'cedar-waxwing', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Brown Creeper', scientificName: 'Certhia americana', emoji: '\ud83d\udc26', summary: 'Spirals upward along tree trunks probing bark crevices for insects — needs large-diameter trees with rough, furrowed bark.', status: 'Declining', page: 'brown-creeper', habitats: ['woodland', 'woodland edge', 'mature forest'] },
  { name: 'Hermit Thrush', scientificName: 'Catharus guttatus', emoji: '\ud83d\udc26', summary: 'Spends winter in deciduous woods foraging in leaf litter — its flute-like song spirals upward in phrases no other bird produces.', status: 'Common', page: 'hermit-thrush', habitats: ['woodland', 'woodland edge', 'leaf litter'] },
  { name: 'Eastern Wood-Pewee', scientificName: 'Contopus virens', emoji: '\ud83d\udc26', summary: 'A flycatcher that catches insects over forest gaps in mid-air — down more than 20% since 1966 as aerial insect biomass falls.', status: 'Declining', page: 'eastern-wood-pewee', habitats: ['woodland', 'woodland edge', 'open canopy'] },
  { name: 'Whip-poor-will', scientificName: 'Antrostomus vociferus', emoji: '\ud83d\udc26', summary: 'A nocturnal insectivore down 69% since 1966 — needs moth-rich nights and leaf-litter nesting sites on open forest floors.', status: 'Declining', page: 'whip-poor-will', habitats: ['woodland', 'woodland edge', 'leaf litter'] },
  { name: 'Ovenbird', scientificName: 'Seiurus aurocapilla', emoji: '\ud83d\udc26', summary: 'Walks forest floors rather than flying — its dome-shaped nest hidden in leaf litter resembles a Dutch bread oven.', status: 'Declining', page: 'ovenbird', habitats: ['woodland', 'leaf litter', 'mature forest'] },
  { name: 'American Goldfinch', scientificName: 'Spinus tristis', emoji: '\ud83d\udc26', summary: 'Builds its plumage brightness directly from carotenoids in seeds — delays nesting until late July when native seed plants reach peak production.', status: 'Common', page: 'american-goldfinch', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Ruby-Throated Hummingbird', scientificName: 'Archilochus colubris', emoji: '\ud83d\udc26', summary: 'The only hummingbird breeding east of the Mississippi — crosses the Gulf of Mexico non-stop on fat reserves built from flower nectar.', status: 'Common', page: 'ruby-throated-hummingbird', habitats: ['garden', 'woodland edge', 'open woodland'] },
  { name: 'Indigo Bunting', scientificName: 'Passerina cyanea', emoji: '\ud83d\udc26', summary: 'The male\'s blue color is structural, not pigment — feather microstructure refracts blue wavelengths. Down 30% since 1970.', status: 'Declining', page: 'indigo-bunting', habitats: ['woodland edge', 'edge', 'shrub'] },
  { name: 'Dark-Eyed Junco', scientificName: 'Junco hyemalis', emoji: '\ud83d\udc26', summary: 'Breeds in northern forests and arrives in yards each winter — forages in leaf litter and flashes white outer tail feathers when flushed.', status: 'Common', page: 'dark-eyed-junco', habitats: ['woodland edge', 'garden', 'leaf litter'] },
  { name: 'American Tree Sparrow', scientificName: 'Spizelloides arborea', emoji: '\ud83d\udc26', summary: 'Breeds in Arctic tundra and visits yards further south each winter — down 53% since 1970 as breeding habitat warms.', status: 'Declining', page: 'american-tree-sparrow', habitats: ['edge', 'garden', 'open land'] },

  // ── MOTHS ─────────────────────────────────────────────────────────────────
  { name: 'Cecropia Moth', scientificName: 'Hyalophora cecropia', emoji: '\ud83e\udd8b', summary: 'The largest moth in North America cannot eat as an adult — it lives entirely on fat reserves built during the caterpillar stage.', status: 'Declining', page: 'cecropia-moth', habitats: ['woodland edge', 'suburban', 'garden'] },
  { name: 'Luna Moth', scientificName: 'Actias luna', emoji: '\ud83e\udd8b', summary: 'A silk moth with pale green wings that lives only one week as an adult — caterpillars feed on native walnut, sweetgum, and birch.', status: 'Declining', page: 'luna-moth', habitats: ['woodland', 'woodland edge', 'suburban'] },
  { name: 'Polyphemus Moth', scientificName: 'Antheraea polyphemus', emoji: '\ud83e\udd8b', summary: 'One of the largest North American moths — false eyespots flash open when disturbed; caterpillars feed on native oaks and maples.', status: 'Declining', page: 'polyphemus-moth', habitats: ['woodland', 'woodland edge', 'suburban'] },
  { name: 'Hummingbird Clearwing Moth', scientificName: 'Hemaris thysbe', emoji: '\ud83e\udd8b', summary: 'A day-flying hawk moth that hovers at flowers like a hummingbird — its wings clear on the first flight, revealing transparent panes between veins.', status: 'Common', page: 'hummingbird-clearwing-moth', habitats: ['garden', 'meadow', 'woodland edge'] },

  // ── BUTTERFLIES ───────────────────────────────────────────────────────────
  { name: 'Eastern Tiger Swallowtail', scientificName: 'Papilio glaucus', emoji: '\ud83e\udd8b', summary: 'The most familiar large butterfly east of the Rockies — caterpillars use wild cherry, tulip poplar, and sassafras.', status: 'Common', page: 'tiger-swallowtail', habitats: ['woodland edge', 'garden', 'meadow'] },
  { name: 'Black Swallowtail', scientificName: 'Papilio polyxenes', emoji: '\ud83e\udd8b', summary: 'Caterpillars feed on carrot-family plants including fennel and dill — overwinters as a chrysalis attached to plant stems.', status: 'Common', page: 'black-swallowtail', habitats: ['garden', 'meadow', 'edge'] },
  { name: 'Spicebush Swallowtail', scientificName: 'Papilio troilus', emoji: '\ud83e\udd8b', summary: 'Caterpillars feed exclusively on spicebush and sassafras — they roll individual leaves into a shelter and rest inside between feedings.', status: 'Common', page: 'spicebush-swallowtail', habitats: ['woodland edge', 'garden', 'thicket'] },
  { name: 'Giant Swallowtail', scientificName: 'Papilio cresphontes', emoji: '\ud83e\udd8b', summary: 'The largest butterfly in North America — its caterpillar mimics a bird dropping resting on the stem of a host plant.', status: 'Common', page: 'giant-swallowtail', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Zebra Swallowtail', scientificName: 'Eurytides marcellus', emoji: '\ud83e\udd8b', summary: 'The only kite-swallowtail in North America — caterpillars feed exclusively on pawpaw leaves, restricting its range to pawpaw habitat.', status: 'Declining', page: 'zebra-swallowtail', habitats: ['woodland edge', 'stream edge', 'pawpaw grove'] },
  { name: 'Great Spangled Fritillary', scientificName: 'Speyeria cybele', emoji: '\ud83e\udd8b', summary: 'Caterpillars feed only on native violets and take a full year to develop — violet-rich woodland edges determine where it breeds.', status: 'Declining', page: 'great-spangled-fritillary', habitats: ['woodland edge', 'meadow', 'edge'] },
  { name: 'Baltimore Checkerspot', scientificName: 'Euphydryas phaeton', emoji: '\ud83e\udd8b', summary: 'Maryland\'s state insect — caterpillars feed in communal groups on turtlehead plants in wet meadows, then overwinter together in leaf litter.', status: 'Endangered', page: 'baltimore-checkerspot', habitats: ['wetland', 'meadow', 'stream edge'] },
  { name: 'Viceroy', scientificName: 'Limenitis archippus', emoji: '\ud83e\udd8b', summary: 'Resembles a Monarch and carries its own bitter compounds — long considered a harmless mimic, it is now understood to be unpalatable on its own terms.', status: 'Declining', page: 'viceroy', habitats: ['wetland edge', 'garden', 'meadow'] },
  { name: 'Red Admiral', scientificName: 'Vanessa atalanta', emoji: '\ud83e\udd8b', summary: 'Basks on flat surfaces to warm up in the morning — caterpillars feed on stinging nettles detected by taste receptors on the female\'s feet.', status: 'Common', page: 'red-admiral', habitats: ['woodland edge', 'garden', 'edge'] },
  { name: 'Painted Lady', scientificName: 'Vanessa cardui', emoji: '\ud83e\udd8b', summary: 'The most widespread butterfly on Earth — makes multigenerational migrations across North America each season.', status: 'Common', page: 'painted-lady', habitats: ['meadow', 'garden', 'open land'] },
  { name: 'American Lady', scientificName: 'Vanessa virginiensis', emoji: '\ud83e\udd8b', summary: 'Caterpillars make silk-wrapped leaf nests on native everlastings and cudweeds — plants most gardeners remove as weeds.', status: 'Common', page: 'american-lady', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Mourning Cloak', scientificName: 'Nymphalis antiopa', emoji: '\ud83e\udd8b', summary: 'One of the longest-lived butterflies in North America — overwinters as an adult under bark and emerges on the first warm days of March.', status: 'Common', page: 'mourning-cloak', habitats: ['woodland edge', 'garden', 'woodland'] },
  { name: 'Question Mark', scientificName: 'Polygonia interrogationis', emoji: '\ud83e\udd8b', summary: 'Named for a small silver punctuation mark on the hindwing underside — overwinters as an adult in bark crevices and hollow logs.', status: 'Common', page: 'question-mark', habitats: ['woodland edge', 'garden', 'edge'] },
  { name: 'Eastern Comma', scientificName: 'Polygonia comma', emoji: '\ud83e\udd8b', summary: 'A jagged-winged anglewing butterfly whose caterpillars feed on elms and nettles — hibernates as an adult through winter.', status: 'Common', page: 'eastern-comma', habitats: ['woodland edge', 'garden', 'edge'] },
  { name: 'Common Buckeye', scientificName: 'Junonia coenia', emoji: '\ud83e\udd8b', summary: 'Large circular eyespots on its wings flash open when a predator approaches — caterpillars feed on native plantains and snapdragons.', status: 'Common', page: 'common-buckeye', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Pearl Crescent', scientificName: 'Phyciodes tharos', emoji: '\ud83e\udd8b', summary: 'Small and orange-brown — caterpillars feed on native asters and complete multiple generations where host plants are abundant.', status: 'Common', page: 'pearl-crescent', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Cloudless Sulphur', scientificName: 'Phoebis sennae', emoji: '\ud83e\udd8b', summary: 'A large yellow butterfly that migrates south each fall in visible streams — caterpillars feed on partridge pea and native sennas.', status: 'Common', page: 'cloudless-sulphur', habitats: ['meadow', 'garden', 'open land'] },
  { name: 'Orange Sulphur', scientificName: 'Colias eurytheme', emoji: '\ud83e\udd8b', summary: 'One of the most abundant open-country butterflies — often hilltopping alongside Clouded Sulphurs; caterpillars feed on clovers.', status: 'Common', page: 'orange-sulphur', habitats: ['meadow', 'garden', 'open land'] },
  { name: 'Clouded Sulphur', scientificName: 'Colias philodice', emoji: '\ud83e\udd8b', summary: 'Often flies alongside the Orange Sulphur — the two species interbreed in areas of overlap, producing hybrid females with blended wing patterns.', status: 'Common', page: 'clouded-sulphur', habitats: ['meadow', 'garden', 'open land'] },
  { name: 'Cabbage White', scientificName: 'Pieris rapae', emoji: '\ud83e\udd8b', summary: 'Introduced from Europe in the 1860s — now the most commonly seen butterfly in North America; caterpillars feed on mustard-family plants.', status: 'Common', page: 'cabbage-white', habitats: ['garden', 'edge', 'meadow'] },
  { name: 'West Virginia White', scientificName: 'Pieris virginiensis', emoji: '\ud83e\udd8b', summary: 'Dependent on native toothworts for caterpillar food — highly vulnerable to garlic mustard invasion, which the female mistakes for a host plant.', status: 'Declining', page: 'west-virginia-white', habitats: ['woodland', 'woodland edge', 'stream edge'] },
  { name: 'Silvery Checkerspot', scientificName: 'Chlosyne nycteis', emoji: '\ud83e\udd8b', summary: 'Caterpillars feed in communal groups on native coneflowers and wingstem in open forest — declining with meadow fragmentation.', status: 'Declining', page: 'silvery-checkerspot', habitats: ['woodland edge', 'meadow', 'stream edge'] },
  { name: 'Spring Azure', scientificName: 'Celastrina ladon', emoji: '\ud83e\udd8b', summary: 'One of the first butterflies of spring — caterpillars feed on the flowers of native dogwood and viburnum before the leaves fully open.', status: 'Common', page: 'spring-azure', habitats: ['woodland edge', 'garden', 'edge'] },
  { name: 'Eastern Tailed-Blue', scientificName: 'Cupido comyntas', emoji: '\ud83e\udd8b', summary: 'One of the smallest butterflies in North America — caterpillars feed on native legumes and produce a secretion that ants tend.', status: 'Common', page: 'eastern-tailed-blue', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Gray Hairstreak', scientificName: 'Strymon melinus', emoji: '\ud83e\udd8b', summary: 'The most widespread hairstreak in North America — caterpillars feed on the flowers and seeds of native legumes and mallows.', status: 'Common', page: 'gray-hairstreak', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Coral Hairstreak', scientificName: 'Satyrium titus', emoji: '\ud83e\udd8b', summary: 'An orange-spotted brown hairstreak without tails — caterpillars feed on wild cherries; adults seek out native milkweed and thistles.', status: 'Declining', page: 'coral-hairstreak', habitats: ['woodland edge', 'meadow', 'thicket'] },
  { name: 'Checkered White', scientificName: 'Pontia protodice', emoji: '\ud83e\udd8b', summary: 'A prairie butterfly that has lost most of its eastern range — still found where native mustard-family plants grow in open sandy ground.', status: 'Declining', page: 'checkered-white', habitats: ['meadow', 'open land', 'edge'] },
  { name: 'Olympia Marble', scientificName: 'Euchloe olympia', emoji: '\ud83e\udd8b', summary: 'An early-spring butterfly with green marbling on the hindwing undersides — restricted to native rock cresses on limestone and sandstone outcrops.', status: 'Declining', page: 'olympia-marble', habitats: ['meadow', 'open land', 'rocky outcrop'] },
  { name: 'Sleepy Orange', scientificName: 'Abaeis nicippe', emoji: '\ud83e\udd8b', summary: 'A fast-flying sulphur of the southeast that expands north each summer — caterpillars feed on native sennas and complete multiple generations.', status: 'Common', page: 'sleepy-orange', habitats: ['meadow', 'open land', 'edge'] },
  { name: 'Little Yellow', scientificName: 'Pyrisitia lisa', emoji: '\ud83e\udd8b', summary: 'A small southern sulphur that wanders north each summer — caterpillars feed on partridge pea and other native legumes.', status: 'Common', page: 'little-yellow', habitats: ['meadow', 'open land', 'garden'] },
  { name: 'Wild Indigo Duskywing', scientificName: 'Erynnis baptisiae', emoji: '\ud83e\udd8b', summary: 'A specialist skipper dependent on wild blue indigo and native baptisia — highly vulnerable to host plant removal and habitat fragmentation.', status: 'Declining', page: 'wild-indigo-duskywing', habitats: ['meadow', 'woodland edge', 'open land'] },
  { name: 'Frosted Elfin', scientificName: 'Callophrys irus', emoji: '\ud83e\udd8b', summary: 'Dependent on wild blue indigo and wild lupine — state-listed as threatened or endangered across most of its range where host plants were removed.', status: 'Declining', page: 'frosted-elfin', habitats: ['meadow', 'open land', 'sandy barrens'] },
  { name: 'Karner Blue', scientificName: 'Lycaeides melissa samuelis', emoji: '\ud83e\udd8b', summary: 'Federally endangered — caterpillars feed only on wild lupine; the entire eastern population depends on oak barrens and sandplain habitats.', status: 'Endangered', page: 'karner-blue', habitats: ['oak barrens', 'sandy barrens', 'open land'] },
  { name: 'Juvenal\'s Duskywing', scientificName: 'Erynnis juvenalis', emoji: '\ud83e\udd8b', summary: 'A spring skipper whose caterpillars feed on native oaks — active only a few weeks each year when oaks are just leafing out.', status: 'Common', page: 'juvenals-duskywing', habitats: ['woodland edge', 'oak woodland', 'edge'] },
  { name: 'Leonard\'s Skipper', scientificName: 'Hesperia leonardus', emoji: '\ud83e\udd8b', summary: 'One of the last butterflies to fly each year — active only in September and dependent on native bunch grasses in undisturbed meadows.', status: 'Declining', page: 'leonards-skipper', habitats: ['meadow', 'prairie', 'edge'] },
  { name: 'Cobweb Skipper', scientificName: 'Hesperia metea', emoji: '\ud83e\udd8b', summary: 'A small brown skipper of open prairies and barrens — caterpillars feed on native bluestem grasses; one of the earliest skippers each spring.', status: 'Declining', page: 'cobweb-skipper', habitats: ['prairie', 'sandy barrens', 'meadow'] },
  { name: 'Henry\'s Elfin', scientificName: 'Callophrys henrici', emoji: '\ud83e\udd8b', summary: 'A specialist butterfly whose caterpillars feed on Eastern Redbud flowers — adults fly only in April and May, timed exactly to redbud bloom.', status: 'Declining', page: 'henrys-elfin', habitats: ['woodland edge', 'garden', 'edge'] },

  // ── HOST TREES ────────────────────────────────────────────────────────────
  { name: 'Hackberry', scientificName: 'Celtis occidentalis', emoji: '\ud83c\udf33', summary: 'A host tree that supports specialist butterflies other plants cannot replace.', status: 'Common', page: 'hackberry', habitats: ['woodland edge', 'suburban', 'garden'] },
  { name: 'Hackberry Emperor', scientificName: 'Asterocampa celtis', emoji: '\ud83e\udd8b', summary: 'A hackberry specialist whose caterpillars depend on leaves and leaf litter beneath the tree.', status: 'Common', page: 'hackberry-emperor', habitats: ['woodland edge', 'suburban', 'garden'] },
  { name: 'American Snout', scientificName: 'Libytheana carinenta', emoji: '\ud83e\udd8b', summary: 'A strange butterfly with elongated palps and a strict dependence on hackberry.', status: 'Common', page: 'american-snout', habitats: ['woodland edge', 'suburban', 'garden'] },
  { name: 'Tawny Emperor', scientificName: 'Asterocampa clyton', emoji: '\ud83e\udd8b', summary: 'Another hackberry-dependent butterfly that disappears when host trees are missing.', status: 'Common', page: 'tawny-emperor', habitats: ['woodland edge', 'suburban', 'garden'] },

  // ── DRAGONFLY ─────────────────────────────────────────────────────────────
  { name: 'Green Darner', scientificName: 'Anax junius', emoji: '\u2728', summary: 'North America\'s most common large dragonfly — migrates in visible flocks of thousands and needs clean water for its aquatic larval stage.', status: 'Declining', page: 'green-darner', habitats: ['wetland', 'pond edge', 'meadow'] },

  // ── NATIVE PLANTS — WILDFLOWERS ───────────────────────────────────────────
  { name: 'Common Milkweed', scientificName: 'Asclepias syriaca', emoji: '\ud83c\udf3f', summary: 'The primary host plant for Monarch caterpillars — also provides late-summer nectar and soft pod fiber that goldfinches use in nests.', status: 'Common', page: 'common-milkweed', habitats: ['meadow', 'edge', 'open land'] },
  { name: 'Swamp Milkweed', scientificName: 'Asclepias incarnata', emoji: '\ud83c\udf3f', summary: 'A monarch host plant suited to wetter conditions — supports the same caterpillar life cycle as common milkweed in rain gardens and low spots.', status: 'Common', page: 'swamp-milkweed', habitats: ['wetland edge', 'garden', 'stream edge'] },
  { name: 'Butterfly Weed', scientificName: 'Asclepias tuberosa', emoji: '\ud83c\udf3f', summary: 'A drought-tolerant milkweed with bright orange flowers — provides nectar for dozens of butterfly species and hosts Monarch caterpillars.', status: 'Common', page: 'butterfly-weed', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Purple Coneflower', scientificName: 'Echinacea purpurea', emoji: '\ud83c\udf3f', summary: 'Feeds specialist native bees in July and goldfinches on dried seed heads from October through January on the same plant.', status: 'Common', page: 'purple-coneflower', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Canada Goldenrod', scientificName: 'Solidago canadensis', emoji: '\ud83c\udf3f', summary: 'Hosts over 100 specialist insect species — its reputation as an allergen is mistaken; windborne ragweed pollen is the actual cause of hay fever.', status: 'Common', page: 'canada-goldenrod', habitats: ['meadow', 'edge', 'open land'] },
  { name: 'New England Aster', scientificName: 'Symphyotrichum novae-angliae', emoji: '\ud83c\udf3f', summary: 'Blooms September–October providing one of the last nectar sources before Monarch butterflies reach the Gulf migration corridor.', status: 'Common', page: 'new-england-aster', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Wild Bergamot', scientificName: 'Monarda fistulosa', emoji: '\ud83c\udf3f', summary: 'Blooms July–August drawing bees, butterflies, and hummingbirds — a native mint that spreads by rhizome in full sun.', status: 'Common', page: 'wild-bergamot', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Joe-Pye Weed', scientificName: 'Eutrochium maculatum', emoji: '\ud83c\udf3f', summary: 'Blooms August–September when nectar becomes scarce — one of the last large native flowers before migrating Monarchs reach the Gulf.', status: 'Common', page: 'joe-pye-weed', habitats: ['meadow', 'wetland edge', 'garden'] },
  { name: 'Wild Columbine', scientificName: 'Aquilegia canadensis', emoji: '\ud83c\udf3f', summary: 'Long red spurs evolved for ruby-throated hummingbird pollination — one of the first native nectar sources available each spring.', status: 'Common', page: 'wild-columbine', habitats: ['woodland edge', 'rocky slope', 'garden'] },
  { name: 'Black-Eyed Susan', scientificName: 'Rudbeckia hirta', emoji: '\ud83c\udf3f', summary: 'Short-lived but self-sowing — provides pollen for specialist sweat bees and nectar for butterflies through the late summer heat.', status: 'Common', page: 'black-eyed-susan', habitats: ['meadow', 'garden', 'edge'] },
  { name: 'Virginia Bluebell', scientificName: 'Mertensia virginica', emoji: '\ud83c\udf3f', summary: 'A spring ephemeral that blooms before the leaf canopy closes — an early nectar source for returning ruby-throated hummingbirds in April.', status: 'Common', page: 'virginia-bluebell', habitats: ['woodland', 'stream edge', 'flood plain'] },
  { name: 'Ironweed', scientificName: 'Vernonia fasciculata', emoji: '\ud83c\udf3f', summary: 'Vivid purple blooms draw migrating Monarchs and swallowtails in August and September alongside goldenrod on the same corridor.', status: 'Common', page: 'ironweed', habitats: ['meadow', 'wetland edge', 'edge'] },
  { name: 'Golden Alexanders', scientificName: 'Zizia aurea', emoji: '\ud83c\udf3f', summary: 'One of the earliest native plants to bloom — provides nectar for spring swallowtails and is a larval host for Black Swallowtail caterpillars.', status: 'Common', page: 'golden-alexanders', habitats: ['woodland edge', 'meadow', 'garden'] },
  { name: 'Partridge Pea', scientificName: 'Chamaecrista fasciculata', emoji: '\ud83c\udf3f', summary: 'A nitrogen-fixing annual that hosts Cloudless Sulphur and Sleepy Orange caterpillars — produces seeds that persist through winter on standing stems.', status: 'Common', page: 'partridge-pea', habitats: ['meadow', 'edge', 'open land'] },
  { name: 'Wild Senna', scientificName: 'Senna hebecarpa', emoji: '\ud83c\udf3f', summary: 'A tall native legume that hosts Cloudless Sulphur caterpillars — its pods persist through winter providing seed for ground-foraging birds.', status: 'Common', page: 'wild-senna', habitats: ['woodland edge', 'meadow', 'wetland edge'] },
  { name: 'Maryland Senna', scientificName: 'Senna marilandica', emoji: '\ud83c\udf3f', summary: 'Blooms July–August with yellow flowers — hosts multiple specialist sulphur caterpillars across moist meadows and woodland edges.', status: 'Common', page: 'maryland-senna', habitats: ['meadow', 'woodland edge', 'edge'] },
  { name: 'Wild Blue Indigo', scientificName: 'Baptisia australis', emoji: '\ud83c\udf3f', summary: 'A deep-rooted prairie legume that fixes nitrogen and hosts Wild Indigo Duskywing and Frosted Elfin caterpillars — slow to establish but lives for decades.', status: 'Common', page: 'wild-blue-indigo', habitats: ['meadow', 'woodland edge', 'prairie'] },
  { name: 'Wild Lupine', scientificName: 'Lupinus perennis', emoji: '\ud83c\udf3f', summary: 'The exclusive caterpillar host for Karner Blue butterfly and a major host for Frosted Elfin — requires sandy, open habitat with periodic disturbance.', status: 'Declining', page: 'wild-lupine', habitats: ['sandy barrens', 'open land', 'oak barrens'] },

  // ── NATIVE PLANTS — TREES & SHRUBS ────────────────────────────────────────
  { name: 'White Oak', scientificName: 'Quercus alba', emoji: '\ud83c\udf33', summary: 'A single mature white oak supports over 500 caterpillar species — every one replaced by a non-native removes this food from the local food web.', status: 'Common', page: 'white-oak', habitats: ['woodland', 'woodland edge', 'suburban'] },
  { name: 'Black Cherry', scientificName: 'Prunus serotina', emoji: '\ud83c\udf33', summary: 'The highest-value caterpillar host tree in the eastern United States — supports 456 species of native Lepidoptera larvae on its leaves.', status: 'Common', page: 'black-cherry', habitats: ['woodland', 'woodland edge', 'edge'] },
  { name: 'Serviceberry', scientificName: 'Amelanchier spp.', emoji: '\ud83c\udf33', summary: 'Produces berries in May when returning neotropical migrants arrive hungry — the same window when most other native fruit has not yet ripened.', status: 'Common', page: 'serviceberry', habitats: ['woodland edge', 'garden', 'edge'] },
  { name: 'Pawpaw', scientificName: 'Asimina triloba', emoji: '\ud83c\udf33', summary: 'The only host plant for Zebra Swallowtail caterpillars — produces the largest edible fruit native to North America in September.', status: 'Declining', page: 'pawpaw', habitats: ['woodland', 'stream edge', 'thicket'] },
  { name: 'Spicebush', scientificName: 'Lindera benzoin', emoji: '\ud83c\udf33', summary: 'Hosts Spicebush Swallowtail and Promethea Moth caterpillars — one of the first shrubs to leaf out each spring, giving larvae an early start.', status: 'Common', page: 'spicebush', habitats: ['woodland', 'woodland edge', 'stream edge'] },
  { name: 'Elderberry', scientificName: 'Sambucus canadensis', emoji: '\ud83c\udf33', summary: 'Produces berries in July–August that sustain over 45 bird species — also hosts dozens of specialist native moth and beetle larvae.', status: 'Common', page: 'elderberry', habitats: ['woodland edge', 'wetland edge', 'garden'] },
  { name: 'Winterberry Holly', scientificName: 'Ilex verticillata', emoji: '\ud83c\udf33', summary: 'Keeps bright red berries through winter — feeds American Robins, Cedar Waxwings, and Hermit Thrushes in December when other fruit is gone.', status: 'Common', page: 'winterberry-holly', habitats: ['wetland edge', 'woodland edge', 'garden'] },
  { name: 'Arrowwood Viburnum', scientificName: 'Viburnum dentatum', emoji: '\ud83c\udf33', summary: 'Berries ripen September–October feeding fall migrants including thrushes and waxwings — flower clusters in May–June draw dozens of native bee species.', status: 'Common', page: 'arrowwood-viburnum', habitats: ['woodland edge', 'garden', 'shrub thicket'] },
  { name: 'Eastern Redbud', scientificName: 'Cercis canadensis', emoji: '\ud83c\udf33', summary: 'Flowers bloom on bare branches in April before leaves emerge — an early nectar source and the exclusive caterpillar host plant for Henry\'s Elfin.', status: 'Common', page: 'redbud', habitats: ['woodland edge', 'garden', 'suburban'] },
  { name: 'Sassafras', scientificName: 'Sassafras albidum', emoji: '\ud83c\udf33', summary: 'Produces three differently shaped leaves on the same branch — hosts Spicebush Swallowtail and Tiger Swallowtail caterpillars.', status: 'Common', page: 'sassafras', habitats: ['woodland edge', 'edge', 'suburban'] },
  { name: 'New Jersey Tea', scientificName: 'Ceanothus americanus', emoji: '\ud83c\udf33', summary: 'A nitrogen-fixing shrub that hosts Spring Azure caterpillars on its flowers — its deep root system survives drought and periodic fire.', status: 'Common', page: 'new-jersey-tea', habitats: ['woodland edge', 'meadow', 'edge'] },
  { name: 'Buttonbush', scientificName: 'Cephalanthus occidentalis', emoji: '\ud83c\udf33', summary: 'Thrives at the water\'s edge where few other shrubs will grow — its round flower clusters draw 15 or more native bee species to the margin.', status: 'Common', page: 'buttonbush', habitats: ['wetland edge', 'pond edge', 'stream edge'] },
  { name: 'Virginia Creeper', scientificName: 'Parthenocissus quinquefolia', emoji: '\ud83c\udf33', summary: 'A native vine with blue-black berries consumed by over 35 bird species each autumn — turns scarlet weeks before most other leaves change.', status: 'Common', page: 'virginia-creeper', habitats: ['woodland edge', 'garden', 'suburban'] },

  // ── NATIVE PLANTS — GRASSES ───────────────────────────────────────────────
  { name: 'Little Bluestem', scientificName: 'Schizachyrium scoparium', emoji: '\ud83c\udf3e', summary: 'The dominant grass of the original tallgrass prairie — turns copper-red in fall and provides overwintering cover for insects and small birds.', status: 'Common', page: 'little-bluestem', habitats: ['meadow', 'prairie', 'edge'] },
  { name: 'Prairie Dropseed', scientificName: 'Sporobolus heterolepis', emoji: '\ud83c\udf3e', summary: 'A fine-textured native bunch grass that produces dense crown cover for ground-nesting beneficial insects and overwintering arthropods.', status: 'Common', page: 'prairie-dropseed', habitats: ['meadow', 'prairie', 'edge'] },
]

interface SpeciesGalleryProps {
  onNavigate: (page: Page) => void
}

const STATUS_COLORS: Record<Status, string> = {
  Common: '#2e7d32',
  Declining: '#f57c00',
  Endangered: '#c62828',
}

export default function SpeciesGallery({ onNavigate }: SpeciesGalleryProps) {
  return (
    <div className="page">
      <section className="hero" style={{ paddingBottom: '1rem' }}>
        <div className="hero__eyebrow">All Species</div>
        <h1>The Species Gallery</h1>
        <p className="hero__lead">
          Browse every wildlife profile Camp Monarch currently tracks. Each card links to a full page with the species story and the yard actions that help.
        </p>
      </section>

      <section aria-label="Species gallery" style={{ display: 'grid', gap: '1rem', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))' }}>
        {SPECIES.map((species) => (
          <button
            key={species.page}
            type="button"
            onClick={() => onNavigate(species.page)}
            className="species-card"
            style={{ cursor: 'pointer', textAlign: 'left', padding: '1rem', border: '1px solid #d7e3d4', borderRadius: '16px', background: '#fff' }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: '0.75rem', alignItems: 'baseline' }}>
              <h2 style={{ margin: 0, fontSize: '1.1rem' }}>{species.emoji} {species.name}</h2>
              <span style={{ color: STATUS_COLORS[species.status], fontWeight: 700, fontSize: '0.85rem' }}>{species.status}</span>
            </div>
            <p style={{ margin: '0.35rem 0 0', fontStyle: 'italic', color: '#4d5b4f' }}>{species.scientificName}</p>
            <p style={{ margin: '0.75rem 0 0', lineHeight: 1.5 }}>{species.summary}</p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem', marginTop: '0.9rem' }}>
              {species.habitats.map((habitat) => (
                <span key={habitat} style={{ background: '#eef4ea', borderRadius: '999px', padding: '0.25rem 0.6rem', fontSize: '0.78rem' }}>
                  {habitat}
                </span>
              ))}
            </div>
          </button>
        ))}
      </section>
    </div>
  )
}
