import { useState, useEffect } from 'react'
import Home from './pages/Home'
import Plants from './pages/Plants'
import SpeciesGallery from './pages/SpeciesGallery'
import MonarchLife from './pages/MonarchLife'
import PlantMilkweed from './pages/PlantMilkweed'
import WhyMonarchs from './pages/WhyMonarchs'
import TheFirstYear from './pages/TheFirstYear'
import TheMigration from './pages/TheMigration'
import RaiseAMonarch from './pages/RaiseAMonarch'
import WaystationGuide from './pages/WaystationGuide'
import HabitatTransformation from './pages/HabitatTransformation'
import LogASighting from './pages/LogASighting'
import TakeAction from './pages/TakeAction'
import TigerSwallowtail from './pages/TigerSwallowtail'
import Monarch from './pages/MonarchLife'
import EasternBluebird from './pages/EasternBluebird'
import AmericanRobin from './pages/AmericanRobin'
import GrayCatbird from './pages/GrayCatbird'
import BaltimoreOriole from './pages/BaltimoreOriole'
import BlackCappedChickadee from './pages/BlackCappedChickadee'
import NorthernCardinal from './pages/NorthernCardinal'
import DownyWoodpecker from './pages/DownyWoodpecker'
import Fireflies from './pages/Fireflies'
import SpicebushSwallowtail from './pages/SpicebushSwallowtail'
import GiantSwallowtail from './pages/GiantSwallowtail'
import Viceroy from './pages/Viceroy'
import EasternComma from './pages/EasternComma'
import QuestionMark from './pages/QuestionMark'
import RedAdmiral from './pages/RedAdmiral'
import PaintedLady from './pages/PaintedLady'
import AmericanLady from './pages/AmericanLady'
import MourningCloak from './pages/MourningCloak'
import ZebraSwallowtail from './pages/ZebraSwallowtail'
import Spicebush from './pages/Spicebush'
import Serviceberry from './pages/Serviceberry'
import WhiteOak from './pages/WhiteOak'
import CommonMilkweed from './pages/CommonMilkweed'
import ButterflyWeed from './pages/ButterflyWeed'
import SwampMilkweed from './pages/SwampMilkweed'
import WildColumbine from './pages/WildColumbine'
import PurpleConeflower from './pages/PurpleConeflower'
import BlackEyedSusan from './pages/BlackEyedSusan'
import NewEnglandAster from './pages/NewEnglandAster'
import CanadaGoldenrod from './pages/CanadaGoldenrod'
import WildBergamot from './pages/WildBergamot'
import CedarWaxwing from './pages/CedarWaxwing'
import GarterSnake from './pages/GarterSnake'
import GreenDarner from './pages/GreenDarner'
import BoxTurtles from './pages/BoxTurtles'
import GreatSpangledFritillary from './pages/GreatSpangledFritillary'
import BlackSwallowtail from './pages/BlackSwallowtail'
import DarkEyedJunco from './pages/DarkEyedJunco'
import AmericanTreeSparrow from './pages/AmericanTreeSparrow'
import EasternChipmunk from './pages/EasternChipmunk'
import EasternGraySquirrel from './pages/EasternGraySquirrel'
import SpringPeeper from './pages/SpringPeeper'
import WoodFrog from './pages/WoodFrog'
import AmericanToad from './pages/AmericanToad'
import LittleBrownBat from './pages/LittleBrownBat'
import WoodThrush from './pages/WoodThrush'
import EasternScreechOwl from './pages/EasternScreechOwl'
import PolyphemusMoth from './pages/PolyphemusMoth'
import LunaMoth from './pages/LunaMoth'
import CommonNighthawk from './pages/CommonNighthawk'
import CecropiaMoth from './pages/CecropiaMoth'
import VirginiaOpossum from './pages/VirginiaOpossum'
import AmericanBumbleBee from './pages/AmericanBumbleBee'
import ChimneySwift from './pages/ChimneySwift'
import PurpleMartin from './pages/PurpleMartin'
import RedTailedHawk from './pages/RedTailedHawk'
import EasternMeadowlark from './pages/EasternMeadowlark'
import AmericanKestrel from './pages/AmericanKestrel'
import BrownThrasher from './pages/BrownThrasher'
import EasternTowhee from './pages/EasternTowhee'
import SongSparrow from './pages/SongSparrow'
import EasternPhoebe from './pages/EasternPhoebe'
import Ovenbird from './pages/Ovenbird'
import EasternWoodPewee from './pages/EasternWoodPewee'
import BrownCreeper from './pages/BrownCreeper'
import YellowRumpedWarbler from './pages/YellowRumpedWarbler'
import HermitThrush from './pages/HermitThrush'
import RubyCrownedKinglet from './pages/RubyCrownedKinglet'
import RubyThroatedHummingbird from './pages/RubyThroatedHummingbird'
import IndigoBunting from './pages/IndigoBunting'
import ScarletTanager from './pages/ScarletTanager'
import NorthernFlicker from './pages/NorthernFlicker'
import NorthernMockingbird from './pages/NorthernMockingbird'
import YellowWarbler from './pages/YellowWarbler'
import AmericanGoldfinch from './pages/AmericanGoldfinch'
import WildTurkey from './pages/WildTurkey'
import EasternMeadowlark as EasternMeadowlarkAlt from './pages/EasternMeadowlark'
import Elderberry from './pages/Elderberry'
import ArrowwoodViburnum from './pages/ArrowwoodViburnum'
import NewJerseyTea from './pages/NewJerseyTea'
import GoldenAlexanders from './pages/GoldenAlexanders'
import JoePyeWeed from './pages/JoePyeWeed'
import Ironweed from './pages/Ironweed'
import WildSenna from './pages/WildSenna'
import MarylandSenna from './pages/MarylandSenna'
import PartridgePea from './pages/PartridgePea'
import LittleBluestem from './pages/LittleBluestem'
import PrairieDropseed from './pages/PrairieDropseed'
import WildBlueIndigo from './pages/WildBlueIndigo'
import WildLupine from './pages/WildLupine'
import VirginiaCreeper from './pages/VirginiaCreeper'
import Buttonbush from './pages/Buttonbush'
import WinterberryHolly from './pages/WinterberryHolly'
import VirginiaBluebell from './pages/VirginiaBluebell'
import Redbud from './pages/Redbud'
import Sassafras from './pages/Sassafras'
import Pawpaw from './pages/Pawpaw'
import BlackCherry from './pages/BlackCherry'
import MourningDove from './pages/MourningDove'
import PearlCrescent from './pages/PearlCrescent'
import CommonBuckeye from './pages/CommonBuckeye'
import BaltimoreCheckerspot from './pages/BaltimoreCheckerspot'
import SilveryCheckerspot from './pages/SilveryCheckerspot'
import CabbageWhite from './pages/CabbageWhite'
import CheckeredWhite from './pages/CheckeredWhite'
import OrangeSulphur from './pages/OrangeSulphur'
import CloudedSulphur from './pages/CloudedSulphur'
import CloudlessSulphur from './pages/CloudlessSulphur'
import SleepyOrange from './pages/SleepyOrange'
import LittleYellow from './pages/LittleYellow'
import GrayHairstreak from './pages/GrayHairstreak'
import CoralHairstreak from './pages/CoralHairstreak'
import HenrysElfin from './pages/HenrysElfin'
import FrostedElfin from './pages/FrostedElfin'
import SpringAzure from './pages/SpringAzure'
import EasternTailedBlue from './pages/EasternTailedBlue'
import AmericanTreeSparrow as AmericanTreeSparrowAlt from './pages/AmericanTreeSparrow'
import OlympiaMarble from './pages/OlympiaMarble'
import WestVirginiaWhite from './pages/WestVirginiaWhite'
import KarnerBlue from './pages/KarnerBlue'
import LeonardsSkipper from './pages/LeonardsSkipper'
import CobwebSkipper from './pages/CobwebSkipper'
import JuvenalsDuskywing from './pages/JuvenalsDuskywing'
import WildIndigoDuskywing from './pages/WildIndigoDuskywing'
import HummingbirdClearwingMoth from './pages/HummingbirdClearwingMoth'
import NativeBees from './pages/NativeBees'
import GrayTreeFrogs from './pages/GrayTreeFrogs'
import WhipPoorWill from './pages/WhipPoorWill'
import EasternChipmunk as EasternChipmunkAlt from './pages/EasternChipmunk'
import VirginiaOpossum as VirginiaOpossumAlt from './pages/VirginiaOpossum'
import AmericanToad as AmericanToadAlt from './pages/AmericanToad'
import PurpleMartin as PurpleMartinAlt from './pages/PurpleMartin'
import Hackberry from './pages/Hackberry'
import HackberryEmperor from './pages/HackberryEmperor'
import AmericanSnout from './pages/AmericanSnout'
import TawnyEmperor from './pages/TawnyEmperor'
import FAQ from './pages/FAQ'
import HOAGuide from './pages/HOAGuide'
import HabitatHero from './pages/HabitatHero'
import HabitatLayers from './pages/HabitatLayers'
import HabitatScore from './pages/HabitatScore'
import TalkingPoints from './pages/TalkingPoints'
import SeasonalCalendar from './pages/SeasonalCalendar'
import PlantsByConditions from './pages/PlantsByConditions'
import PlantsStarterPlants from './pages/PlantsStarterPlants'
import PlantsHostPlants from './pages/PlantsHostPlants'
import PlantsMilkweeds from './pages/PlantsMilkweeds'
import PlantsBloomCalendar from './pages/PlantsBloomCalendar'
import PlantsByFamily from './pages/PlantsByFamily'
import PlantsByPurpose from './pages/PlantsByPurpose'
import PlantsSpeciesIndex from './pages/PlantsSpeciesIndex'
import PlantsGettingStarted from './pages/PlantsGettingStarted'
import PlantCommunities from './pages/PlantCommunities'
import PlantCommonMistakes from './pages/PlantCommonMistakes'
import PlantsLibrary from './pages/PlantsLibrary'
import PlantsFinder from './pages/PlantsFinder'
import NativePlantNearMe from './pages/NativePlantNearMe'
import InvasivePlants from './pages/InvasivePlants'
import PesticideGuide from './pages/PesticideGuide'
import WaterForWildlife from './pages/WaterForWildlife'
import LeaveTheLeaves from './pages/LeaveTheLeaves'
import SpringChecklist from './pages/SpringChecklist'
import AmericanKestrel as AmericanKestrelAlt from './pages/AmericanKestrel'
import EasternBluebird as EasternBluebirdAlt from './pages/EasternBluebird'
import EasternScreechOwl as EasternScreechOwlAlt from './pages/EasternScreechOwl'

export type Page =
  | 'home'
  | 'plants'
  | 'species-gallery'
  | 'monarch-life'
  | 'plant-milkweed'
  | 'why-monarchs'
  | 'the-first-year'
  | 'the-migration'
  | 'raise-a-monarch'
  | 'waystation-guide'
  | 'habitat-transformation'
  | 'log-a-sighting'
  | 'take-action'
  | 'tiger-swallowtail'
  | 'eastern-bluebird'
  | 'american-robin'
  | 'gray-catbird'
  | 'baltimore-oriole'
  | 'black-capped-chickadee'
  | 'northern-cardinal'
  | 'downy-woodpecker'
  | 'fireflies'
  | 'spicebush-swallowtail'
  | 'giant-swallowtail'
  | 'viceroy'
  | 'eastern-comma'
  | 'question-mark'
  | 'red-admiral'
  | 'painted-lady'
  | 'american-lady'
  | 'mourning-cloak'
  | 'zebra-swallowtail'
  | 'spicebush'
  | 'serviceberry'
  | 'white-oak'
  | 'common-milkweed'
  | 'butterfly-weed'
  | 'swamp-milkweed'
  | 'wild-columbine'
  | 'purple-coneflower'
  | 'black-eyed-susan'
  | 'new-england-aster'
  | 'canada-goldenrod'
  | 'wild-bergamot'
  | 'cedar-waxwing'
  | 'garter-snake'
  | 'green-darner'
  | 'box-turtles'
  | 'great-spangled-fritillary'
  | 'black-swallowtail'
  | 'dark-eyed-junco'
  | 'american-tree-sparrow'
  | 'eastern-chipmunk'
  | 'eastern-gray-squirrel'
  | 'spring-peeper'
  | 'wood-frog'
  | 'toad'
  | 'little-brown-bat'
  | 'wood-thrush'
  | 'eastern-screech-owl'
  | 'polyphemus-moth'
  | 'luna-moth'
  | 'common-nighthawk'
  | 'cecropia-moth'
  | 'virginia-opossum'
  | 'american-bumble-bee'
  | 'chimney-swift'
  | 'purple-martin'
  | 'red-tailed-hawk'
  | 'eastern-meadowlark'
  | 'american-kestrel'
  | 'brown-thrasher'
  | 'eastern-towhee'
  | 'song-sparrow'
  | 'eastern-phoebe'
  | 'ovenbird'
  | 'eastern-wood-pewee'
  | 'brown-creeper'
  | 'yellow-rumped-warbler'
  | 'hermit-thrush'
  | 'ruby-crowned-kinglet'
  | 'ruby-throated-hummingbird'
  | 'indigo-bunting'
  | 'scarlet-tanager'
  | 'northern-flicker'
  | 'northern-mockingbird'
  | 'yellow-warbler'
  | 'american-goldfinch'
  | 'wild-turkey'
  | 'elderberry'
  | 'arrowwood-viburnum'
  | 'new-jersey-tea'
  | 'golden-alexanders'
  | 'joe-pye-weed'
  | 'ironweed'
  | 'wild-senna'
  | 'maryland-senna'
  | 'partridge-pea'
  | 'little-bluestem'
  | 'prairie-dropseed'
  | 'wild-blue-indigo'
  | 'wild-lupine'
  | 'virginia-creeper'
  | 'buttonbush'
  | 'winterberry-holly'
  | 'virginia-bluebell'
  | 'redbud'
  | 'sassafras'
  | 'pawpaw'
  | 'black-cherry'
  | 'mourning-dove'
  | 'pearl-crescent'
  | 'common-buckeye'
  | 'baltimore-checkerspot'
  | 'silvery-checkerspot'
  | 'cabbage-white'
  | 'checkered-white'
  | 'orange-sulphur'
  | 'clouded-sulphur'
  | 'cloudless-sulphur'
  | 'sleepy-orange'
  | 'little-yellow'
  | 'gray-hairstreak'
  | 'coral-hairstreak'
  | 'henrys-elfin'
  | 'frosted-elfin'
  | 'spring-azure'
  | 'eastern-tailed-blue'
  | 'olympia-marble'
  | 'west-virginia-white'
  | 'karner-blue'
  | 'leonards-skipper'
  | 'cobweb-skipper'
  | 'juvenals-duskywing'
  | 'wild-indigo-duskywing'
  | 'hummingbird-clearwing-moth'
  | 'native-bees'
  | 'gray-tree-frogs'
  | 'whip-poor-will'
  | 'hackberry'
  | 'hackberry-emperor'
  | 'american-snout'
  | 'tawny-emperor'
  | 'faq'
  | 'hoa-guide'
  | 'habitat-hero'
  | 'habitat-layers'
  | 'habitat-score'
  | 'talking-points'
  | 'seasonal-calendar'
  | 'plants-by-conditions'
  | 'plants-starter-plants'
  | 'plants-host-plants'
  | 'plants-milkweeds'
  | 'plants-bloom-calendar'
  | 'plants-by-family'
  | 'plants-by-purpose'
  | 'plants-species-index'
  | 'plants-getting-started'
  | 'plant-communities'
  | 'plant-common-mistakes'
  | 'plants-library'
  | 'plants-finder'
  | 'native-plant-near-me'
  | 'invasive-plants'
  | 'pesticide-guide'
  | 'water-for-wildlife'
  | 'leave-the-leaves'
  | 'spring-checklist'
  | 'choose-a-plant'
  | 'whip-poor-will'
